# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from axern.control.tunnel.v1 import tunnel_pb2 as axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in axern/control/tunnel/v1/tunnel_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TunnelControlStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTunnelSession = channel.unary_unary(
                '/axern.control.tunnel.v1.TunnelControl/CreateTunnelSession',
                request_serializer=axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.CreateTunnelSessionRequest.SerializeToString,
                response_deserializer=axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.CreateTunnelSessionResponse.FromString,
                _registered_method=True)
        self.GetTunnelSession = channel.unary_unary(
                '/axern.control.tunnel.v1.TunnelControl/GetTunnelSession',
                request_serializer=axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.GetTunnelSessionRequest.SerializeToString,
                response_deserializer=axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.GetTunnelSessionResponse.FromString,
                _registered_method=True)
        self.ListTunnelSessions = channel.unary_unary(
                '/axern.control.tunnel.v1.TunnelControl/ListTunnelSessions',
                request_serializer=axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.ListTunnelSessionsRequest.SerializeToString,
                response_deserializer=axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.ListTunnelSessionsResponse.FromString,
                _registered_method=True)
        self.ListTunnelSessionEvents = channel.unary_unary(
                '/axern.control.tunnel.v1.TunnelControl/ListTunnelSessionEvents',
                request_serializer=axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.ListTunnelSessionEventsRequest.SerializeToString,
                response_deserializer=axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.ListTunnelSessionEventsResponse.FromString,
                _registered_method=True)
        self.InspectTunnelSession = channel.unary_unary(
                '/axern.control.tunnel.v1.TunnelControl/InspectTunnelSession',
                request_serializer=axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.InspectTunnelSessionRequest.SerializeToString,
                response_deserializer=axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.InspectTunnelSessionResponse.FromString,
                _registered_method=True)
        self.RevokeTunnelSession = channel.unary_unary(
                '/axern.control.tunnel.v1.TunnelControl/RevokeTunnelSession',
                request_serializer=axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.RevokeTunnelSessionRequest.SerializeToString,
                response_deserializer=axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.RevokeTunnelSessionResponse.FromString,
                _registered_method=True)
        self.RenewTunnelSession = channel.unary_unary(
                '/axern.control.tunnel.v1.TunnelControl/RenewTunnelSession',
                request_serializer=axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.RenewTunnelSessionRequest.SerializeToString,
                response_deserializer=axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.RenewTunnelSessionResponse.FromString,
                _registered_method=True)


class TunnelControlServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateTunnelSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTunnelSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTunnelSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTunnelSessionEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InspectTunnelSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeTunnelSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewTunnelSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TunnelControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTunnelSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTunnelSession,
                    request_deserializer=axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.CreateTunnelSessionRequest.FromString,
                    response_serializer=axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.CreateTunnelSessionResponse.SerializeToString,
            ),
            'GetTunnelSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTunnelSession,
                    request_deserializer=axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.GetTunnelSessionRequest.FromString,
                    response_serializer=axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.GetTunnelSessionResponse.SerializeToString,
            ),
            'ListTunnelSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTunnelSessions,
                    request_deserializer=axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.ListTunnelSessionsRequest.FromString,
                    response_serializer=axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.ListTunnelSessionsResponse.SerializeToString,
            ),
            'ListTunnelSessionEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTunnelSessionEvents,
                    request_deserializer=axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.ListTunnelSessionEventsRequest.FromString,
                    response_serializer=axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.ListTunnelSessionEventsResponse.SerializeToString,
            ),
            'InspectTunnelSession': grpc.unary_unary_rpc_method_handler(
                    servicer.InspectTunnelSession,
                    request_deserializer=axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.InspectTunnelSessionRequest.FromString,
                    response_serializer=axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.InspectTunnelSessionResponse.SerializeToString,
            ),
            'RevokeTunnelSession': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeTunnelSession,
                    request_deserializer=axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.RevokeTunnelSessionRequest.FromString,
                    response_serializer=axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.RevokeTunnelSessionResponse.SerializeToString,
            ),
            'RenewTunnelSession': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewTunnelSession,
                    request_deserializer=axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.RenewTunnelSessionRequest.FromString,
                    response_serializer=axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.RenewTunnelSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'axern.control.tunnel.v1.TunnelControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('axern.control.tunnel.v1.TunnelControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TunnelControl:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTunnelSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.control.tunnel.v1.TunnelControl/CreateTunnelSession',
            axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.CreateTunnelSessionRequest.SerializeToString,
            axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.CreateTunnelSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTunnelSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.control.tunnel.v1.TunnelControl/GetTunnelSession',
            axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.GetTunnelSessionRequest.SerializeToString,
            axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.GetTunnelSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTunnelSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.control.tunnel.v1.TunnelControl/ListTunnelSessions',
            axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.ListTunnelSessionsRequest.SerializeToString,
            axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.ListTunnelSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTunnelSessionEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.control.tunnel.v1.TunnelControl/ListTunnelSessionEvents',
            axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.ListTunnelSessionEventsRequest.SerializeToString,
            axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.ListTunnelSessionEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InspectTunnelSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.control.tunnel.v1.TunnelControl/InspectTunnelSession',
            axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.InspectTunnelSessionRequest.SerializeToString,
            axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.InspectTunnelSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeTunnelSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.control.tunnel.v1.TunnelControl/RevokeTunnelSession',
            axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.RevokeTunnelSessionRequest.SerializeToString,
            axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.RevokeTunnelSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenewTunnelSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.control.tunnel.v1.TunnelControl/RenewTunnelSession',
            axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.RenewTunnelSessionRequest.SerializeToString,
            axern_dot_control_dot_tunnel_dot_v1_dot_tunnel__pb2.RenewTunnelSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
