version: 2

updates:
  - package-ecosystem: "gomod"
    directories:
      - "**/*"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    groups:
      go-security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    groups:
      rust-security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    groups:
      typescript-security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    groups:
      python-security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    groups:
      actions-security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
