"""Python SDK for the Axern control plane."""

from axern_sdk.catalog import CatalogClient
from axern_sdk.async_client import AsyncAxernClient
from axern_sdk.client import AxernClient
from axern_sdk.context import AxernContext, TLSContext, load_context
from axern_sdk.errors import (
    AxernError,
    AxernTimeoutError,
    SandboxCancelledError,
    SandboxCapabilityErrorInfo,
    SandboxConnectionError,
    SandboxError,
    SandboxExecError,
    SandboxExecutionError,
    SandboxLifecycleError,
    SandboxNotFoundError,
    SandboxPermissionError,
    SandboxNotStartedError,
    SandboxPreconditionError,
    SandboxRpcError,
    SandboxTimeoutError,
    SandboxValidationError,
    sandbox_capability_error_info,
)
from axern_sdk.catalog.models import (
    MountSpec,
    OciImageDescriptor,
    RuntimeBaselinePolicy,
    RuntimeCapabilities,
    RuntimeCapabilityPolicy,
    RuntimeExecutionProfile,
    RuntimeNetworkNamespacePolicy,
    RuntimeResourcePolicy,
    RuntimeTemplate,
)
from axern_sdk.function import (
    Function,
    FunctionInvocationError,
    FunctionInvocationResult,
    FunctionPackage,
    FunctionResources,
    FunctionScaling,
    FunctionSource,
    FunctionSpec,
    FunctionWorkerSource,
    load_function_spec,
)
from axern_sdk.models import HTTPProbe, ImageMount, SecretEnvVar, SecretFile, ServiceProbe, TCPProbe, VolumeMount
from axern_sdk.node import (
    AsyncNodeSandboxClient,
    AsyncProcessResult,
    AsyncSandboxProcess,
    BrowserStatus,
    CapabilityDependencyStatus,
    CapabilityProviderStatus,
    CapabilityProviderSummary,
    CapabilityStatus,
    ComputerUseDisplay,
    ComputerUseDependencyStatus,
    ComputerUseRegion,
    ComputerUseScreenshot,
    ComputerUseStatus,
    ExecCommand,
    ExecResult,
    ExecStreamEvent,
    ImageProcessMount,
    NodeSandboxClient,
    ProcessResult,
    SandboxProcess,
    workspace_mount,
)
from axern_sdk.sandbox import AsyncSandbox, Sandbox, SandboxFileInfo, SandboxFileKind, SandboxMetadata, SandboxState
from axern_sdk.tunnel import ConnectorConfig, TunnelConnector

__version__ = "0.4.1"

__all__ = [
    "AxernError",
    "AxernTimeoutError",
    "SandboxCancelledError",
    "SandboxCapabilityErrorInfo",
    "SandboxConnectionError",
    "SandboxError",
    "SandboxExecError",
    "SandboxExecutionError",
    "SandboxLifecycleError",
    "SandboxNotFoundError",
    "SandboxPermissionError",
    "SandboxNotStartedError",
    "SandboxPreconditionError",
    "SandboxRpcError",
    "SandboxTimeoutError",
    "SandboxValidationError",
    "sandbox_capability_error_info",
    "AsyncAxernClient",
    "AxernClient",
    "AxernContext",
    "CatalogClient",
    "AsyncNodeSandboxClient",
    "AsyncProcessResult",
    "AsyncSandbox",
    "AsyncSandboxProcess",
    "BrowserStatus",
    "CapabilityDependencyStatus",
    "CapabilityProviderStatus",
    "CapabilityProviderSummary",
    "CapabilityStatus",
    "ComputerUseDisplay",
    "ComputerUseDependencyStatus",
    "ComputerUseRegion",
    "ComputerUseScreenshot",
    "ComputerUseStatus",
    "ExecCommand",
    "ExecResult",
    "ExecStreamEvent",
    "ImageProcessMount",
    "Function",
    "FunctionInvocationError",
    "FunctionInvocationResult",
    "FunctionPackage",
    "FunctionResources",
    "FunctionScaling",
    "FunctionSource",
    "FunctionSpec",
    "FunctionWorkerSource",
    "HTTPProbe",
    "ImageMount",
    "NodeSandboxClient",
    "ProcessResult",
    "Sandbox",
    "SandboxFileInfo",
    "SandboxFileKind",
    "SandboxMetadata",
    "SandboxProcess",
    "SandboxState",
    "ConnectorConfig",
    "TunnelConnector",
    "MountSpec",
    "OciImageDescriptor",
    "RuntimeBaselinePolicy",
    "RuntimeCapabilities",
    "RuntimeCapabilityPolicy",
    "RuntimeExecutionProfile",
    "RuntimeNetworkNamespacePolicy",
    "RuntimeResourcePolicy",
    "RuntimeTemplate",
    "ServiceProbe",
    "SecretEnvVar",
    "SecretFile",
    "TCPProbe",
    "TLSContext",
    "VolumeMount",
    "workspace_mount",
    "load_function_spec",
    "load_context",
]


def platform_name() -> str:
    return "axern"
