# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from axern.node.sandbox.v1 import node_pb2 as axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in axern/node/sandbox/v1/node_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeSandboxStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Exec = channel.unary_unary(
                '/axern.node.sandbox.v1.NodeSandbox/Exec',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ExecRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ExecResponse.FromString,
                _registered_method=True)
        self.ExecStream = channel.stream_stream(
                '/axern.node.sandbox.v1.NodeSandbox/ExecStream',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ExecStreamRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ExecStreamResponse.FromString,
                _registered_method=True)
        self.Process = channel.stream_stream(
                '/axern.node.sandbox.v1.NodeSandbox/Process',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ProcessRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ProcessResponse.FromString,
                _registered_method=True)
        self.ExecImage = channel.unary_unary(
                '/axern.node.sandbox.v1.NodeSandbox/ExecImage',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ExecImageRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ExecImageResponse.FromString,
                _registered_method=True)
        self.ProcessImage = channel.stream_stream(
                '/axern.node.sandbox.v1.NodeSandbox/ProcessImage',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ProcessImageRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ProcessImageResponse.FromString,
                _registered_method=True)
        self.WaitSandbox = channel.unary_unary(
                '/axern.node.sandbox.v1.NodeSandbox/WaitSandbox',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.WaitSandboxRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.WaitSandboxResponse.FromString,
                _registered_method=True)
        self.CapabilityStatus = channel.unary_unary(
                '/axern.node.sandbox.v1.NodeSandbox/CapabilityStatus',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.CapabilityStatusRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.CapabilityStatusResponse.FromString,
                _registered_method=True)
        self.ProxyHTTP = channel.stream_stream(
                '/axern.node.sandbox.v1.NodeSandbox/ProxyHTTP',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ProxyHTTPRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ProxyHTTPResponse.FromString,
                _registered_method=True)
        self.StatFile = channel.unary_unary(
                '/axern.node.sandbox.v1.NodeSandbox/StatFile',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.StatFileRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.StatFileResponse.FromString,
                _registered_method=True)
        self.ListDir = channel.unary_unary(
                '/axern.node.sandbox.v1.NodeSandbox/ListDir',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ListDirRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ListDirResponse.FromString,
                _registered_method=True)
        self.ReadFile = channel.unary_unary(
                '/axern.node.sandbox.v1.NodeSandbox/ReadFile',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ReadFileRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ReadFileResponse.FromString,
                _registered_method=True)
        self.WriteFile = channel.unary_unary(
                '/axern.node.sandbox.v1.NodeSandbox/WriteFile',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.WriteFileRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.WriteFileResponse.FromString,
                _registered_method=True)
        self.MaterializeTaskAssets = channel.unary_unary(
                '/axern.node.sandbox.v1.NodeSandbox/MaterializeTaskAssets',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.MaterializeTaskAssetsRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.MaterializeTaskAssetsResponse.FromString,
                _registered_method=True)
        self.Mkdir = channel.unary_unary(
                '/axern.node.sandbox.v1.NodeSandbox/Mkdir',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.MkdirRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.MkdirResponse.FromString,
                _registered_method=True)
        self.Remove = channel.unary_unary(
                '/axern.node.sandbox.v1.NodeSandbox/Remove',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.RemoveRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.RemoveResponse.FromString,
                _registered_method=True)
        self.Exists = channel.unary_unary(
                '/axern.node.sandbox.v1.NodeSandbox/Exists',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ExistsRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ExistsResponse.FromString,
                _registered_method=True)
        self.Copy = channel.unary_unary(
                '/axern.node.sandbox.v1.NodeSandbox/Copy',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.CopyRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.CopyResponse.FromString,
                _registered_method=True)
        self.Move = channel.unary_unary(
                '/axern.node.sandbox.v1.NodeSandbox/Move',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.MoveRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.MoveResponse.FromString,
                _registered_method=True)
        self.Chmod = channel.unary_unary(
                '/axern.node.sandbox.v1.NodeSandbox/Chmod',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ChmodRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ChmodResponse.FromString,
                _registered_method=True)
        self.Touch = channel.unary_unary(
                '/axern.node.sandbox.v1.NodeSandbox/Touch',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.TouchRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.TouchResponse.FromString,
                _registered_method=True)
        self.UploadArchive = channel.stream_unary(
                '/axern.node.sandbox.v1.NodeSandbox/UploadArchive',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.UploadArchiveRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.UploadArchiveResponse.FromString,
                _registered_method=True)
        self.DownloadArchive = channel.unary_stream(
                '/axern.node.sandbox.v1.NodeSandbox/DownloadArchive',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.DownloadArchiveRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.DownloadArchiveResponse.FromString,
                _registered_method=True)
        self.ComputerUseStatus = channel.unary_unary(
                '/axern.node.sandbox.v1.NodeSandbox/ComputerUseStatus',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ComputerUseStatusRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ComputerUseStatusResponse.FromString,
                _registered_method=True)
        self.ComputerUseScreenshot = channel.unary_unary(
                '/axern.node.sandbox.v1.NodeSandbox/ComputerUseScreenshot',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ComputerUseScreenshotRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ComputerUseScreenshotResponse.FromString,
                _registered_method=True)
        self.ComputerUseDisplay = channel.unary_unary(
                '/axern.node.sandbox.v1.NodeSandbox/ComputerUseDisplay',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ComputerUseDisplayRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ComputerUseDisplayResponse.FromString,
                _registered_method=True)
        self.ComputerUseMouse = channel.unary_unary(
                '/axern.node.sandbox.v1.NodeSandbox/ComputerUseMouse',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ComputerUseMouseRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ComputerUseMouseResponse.FromString,
                _registered_method=True)
        self.ComputerUseKeyboard = channel.unary_unary(
                '/axern.node.sandbox.v1.NodeSandbox/ComputerUseKeyboard',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ComputerUseKeyboardRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ComputerUseKeyboardResponse.FromString,
                _registered_method=True)
        self.BrowserStatus = channel.unary_unary(
                '/axern.node.sandbox.v1.NodeSandbox/BrowserStatus',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserStatusRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserStatusResponse.FromString,
                _registered_method=True)
        self.BrowserOpen = channel.unary_unary(
                '/axern.node.sandbox.v1.NodeSandbox/BrowserOpen',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserOpenRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserStatusResponse.FromString,
                _registered_method=True)
        self.BrowserClose = channel.unary_unary(
                '/axern.node.sandbox.v1.NodeSandbox/BrowserClose',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserCloseRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserStatusResponse.FromString,
                _registered_method=True)
        self.BrowserNavigate = channel.unary_unary(
                '/axern.node.sandbox.v1.NodeSandbox/BrowserNavigate',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserNavigateRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserStatusResponse.FromString,
                _registered_method=True)
        self.BrowserResize = channel.unary_unary(
                '/axern.node.sandbox.v1.NodeSandbox/BrowserResize',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserResizeRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserStatusResponse.FromString,
                _registered_method=True)
        self.BrowserClick = channel.unary_unary(
                '/axern.node.sandbox.v1.NodeSandbox/BrowserClick',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserClickRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserStatusResponse.FromString,
                _registered_method=True)
        self.BrowserType = channel.unary_unary(
                '/axern.node.sandbox.v1.NodeSandbox/BrowserType',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserTypeRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserStatusResponse.FromString,
                _registered_method=True)
        self.BrowserWait = channel.unary_unary(
                '/axern.node.sandbox.v1.NodeSandbox/BrowserWait',
                request_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserWaitRequest.SerializeToString,
                response_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserStatusResponse.FromString,
                _registered_method=True)


class NodeSandboxServicer:
    """Missing associated documentation comment in .proto file."""

    def Exec(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Process(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessImage(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WaitSandbox(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CapabilityStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProxyHTTP(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StatFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MaterializeTaskAssets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Mkdir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Copy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Move(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chmod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Touch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadArchive(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadArchive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputerUseStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputerUseScreenshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputerUseDisplay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputerUseMouse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputerUseKeyboard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BrowserStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BrowserOpen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BrowserClose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BrowserNavigate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BrowserResize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BrowserClick(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BrowserType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BrowserWait(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeSandboxServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Exec': grpc.unary_unary_rpc_method_handler(
                    servicer.Exec,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ExecRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ExecResponse.SerializeToString,
            ),
            'ExecStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ExecStream,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ExecStreamRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ExecStreamResponse.SerializeToString,
            ),
            'Process': grpc.stream_stream_rpc_method_handler(
                    servicer.Process,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ProcessRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ProcessResponse.SerializeToString,
            ),
            'ExecImage': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecImage,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ExecImageRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ExecImageResponse.SerializeToString,
            ),
            'ProcessImage': grpc.stream_stream_rpc_method_handler(
                    servicer.ProcessImage,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ProcessImageRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ProcessImageResponse.SerializeToString,
            ),
            'WaitSandbox': grpc.unary_unary_rpc_method_handler(
                    servicer.WaitSandbox,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.WaitSandboxRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.WaitSandboxResponse.SerializeToString,
            ),
            'CapabilityStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.CapabilityStatus,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.CapabilityStatusRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.CapabilityStatusResponse.SerializeToString,
            ),
            'ProxyHTTP': grpc.stream_stream_rpc_method_handler(
                    servicer.ProxyHTTP,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ProxyHTTPRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ProxyHTTPResponse.SerializeToString,
            ),
            'StatFile': grpc.unary_unary_rpc_method_handler(
                    servicer.StatFile,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.StatFileRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.StatFileResponse.SerializeToString,
            ),
            'ListDir': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDir,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ListDirRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ListDirResponse.SerializeToString,
            ),
            'ReadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ReadFileRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ReadFileResponse.SerializeToString,
            ),
            'WriteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteFile,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.WriteFileRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.WriteFileResponse.SerializeToString,
            ),
            'MaterializeTaskAssets': grpc.unary_unary_rpc_method_handler(
                    servicer.MaterializeTaskAssets,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.MaterializeTaskAssetsRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.MaterializeTaskAssetsResponse.SerializeToString,
            ),
            'Mkdir': grpc.unary_unary_rpc_method_handler(
                    servicer.Mkdir,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.MkdirRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.MkdirResponse.SerializeToString,
            ),
            'Remove': grpc.unary_unary_rpc_method_handler(
                    servicer.Remove,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.RemoveRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.RemoveResponse.SerializeToString,
            ),
            'Exists': grpc.unary_unary_rpc_method_handler(
                    servicer.Exists,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ExistsRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ExistsResponse.SerializeToString,
            ),
            'Copy': grpc.unary_unary_rpc_method_handler(
                    servicer.Copy,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.CopyRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.CopyResponse.SerializeToString,
            ),
            'Move': grpc.unary_unary_rpc_method_handler(
                    servicer.Move,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.MoveRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.MoveResponse.SerializeToString,
            ),
            'Chmod': grpc.unary_unary_rpc_method_handler(
                    servicer.Chmod,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ChmodRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ChmodResponse.SerializeToString,
            ),
            'Touch': grpc.unary_unary_rpc_method_handler(
                    servicer.Touch,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.TouchRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.TouchResponse.SerializeToString,
            ),
            'UploadArchive': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadArchive,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.UploadArchiveRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.UploadArchiveResponse.SerializeToString,
            ),
            'DownloadArchive': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadArchive,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.DownloadArchiveRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.DownloadArchiveResponse.SerializeToString,
            ),
            'ComputerUseStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputerUseStatus,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ComputerUseStatusRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ComputerUseStatusResponse.SerializeToString,
            ),
            'ComputerUseScreenshot': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputerUseScreenshot,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ComputerUseScreenshotRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ComputerUseScreenshotResponse.SerializeToString,
            ),
            'ComputerUseDisplay': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputerUseDisplay,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ComputerUseDisplayRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ComputerUseDisplayResponse.SerializeToString,
            ),
            'ComputerUseMouse': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputerUseMouse,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ComputerUseMouseRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ComputerUseMouseResponse.SerializeToString,
            ),
            'ComputerUseKeyboard': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputerUseKeyboard,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ComputerUseKeyboardRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ComputerUseKeyboardResponse.SerializeToString,
            ),
            'BrowserStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.BrowserStatus,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserStatusRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserStatusResponse.SerializeToString,
            ),
            'BrowserOpen': grpc.unary_unary_rpc_method_handler(
                    servicer.BrowserOpen,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserOpenRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserStatusResponse.SerializeToString,
            ),
            'BrowserClose': grpc.unary_unary_rpc_method_handler(
                    servicer.BrowserClose,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserCloseRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserStatusResponse.SerializeToString,
            ),
            'BrowserNavigate': grpc.unary_unary_rpc_method_handler(
                    servicer.BrowserNavigate,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserNavigateRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserStatusResponse.SerializeToString,
            ),
            'BrowserResize': grpc.unary_unary_rpc_method_handler(
                    servicer.BrowserResize,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserResizeRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserStatusResponse.SerializeToString,
            ),
            'BrowserClick': grpc.unary_unary_rpc_method_handler(
                    servicer.BrowserClick,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserClickRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserStatusResponse.SerializeToString,
            ),
            'BrowserType': grpc.unary_unary_rpc_method_handler(
                    servicer.BrowserType,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserTypeRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserStatusResponse.SerializeToString,
            ),
            'BrowserWait': grpc.unary_unary_rpc_method_handler(
                    servicer.BrowserWait,
                    request_deserializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserWaitRequest.FromString,
                    response_serializer=axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'axern.node.sandbox.v1.NodeSandbox', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('axern.node.sandbox.v1.NodeSandbox', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeSandbox:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Exec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/Exec',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ExecRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ExecResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/ExecStream',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ExecStreamRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ExecStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Process(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/Process',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ProcessRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ProcessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/ExecImage',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ExecImageRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ExecImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessImage(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/ProcessImage',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ProcessImageRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ProcessImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WaitSandbox(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/WaitSandbox',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.WaitSandboxRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.WaitSandboxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CapabilityStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/CapabilityStatus',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.CapabilityStatusRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.CapabilityStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProxyHTTP(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/ProxyHTTP',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ProxyHTTPRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ProxyHTTPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StatFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/StatFile',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.StatFileRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.StatFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/ListDir',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ListDirRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ListDirResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/ReadFile',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ReadFileRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ReadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/WriteFile',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.WriteFileRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.WriteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MaterializeTaskAssets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/MaterializeTaskAssets',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.MaterializeTaskAssetsRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.MaterializeTaskAssetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Mkdir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/Mkdir',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.MkdirRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.MkdirResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/Remove',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.RemoveRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.RemoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/Exists',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ExistsRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ExistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Copy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/Copy',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.CopyRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.CopyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Move(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/Move',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.MoveRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.MoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chmod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/Chmod',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ChmodRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ChmodResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Touch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/Touch',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.TouchRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.TouchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadArchive(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/UploadArchive',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.UploadArchiveRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.UploadArchiveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadArchive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/DownloadArchive',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.DownloadArchiveRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.DownloadArchiveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComputerUseStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/ComputerUseStatus',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ComputerUseStatusRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ComputerUseStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComputerUseScreenshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/ComputerUseScreenshot',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ComputerUseScreenshotRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ComputerUseScreenshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComputerUseDisplay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/ComputerUseDisplay',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ComputerUseDisplayRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ComputerUseDisplayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComputerUseMouse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/ComputerUseMouse',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ComputerUseMouseRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ComputerUseMouseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComputerUseKeyboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/ComputerUseKeyboard',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ComputerUseKeyboardRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.ComputerUseKeyboardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BrowserStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/BrowserStatus',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserStatusRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BrowserOpen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/BrowserOpen',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserOpenRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BrowserClose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/BrowserClose',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserCloseRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BrowserNavigate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/BrowserNavigate',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserNavigateRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BrowserResize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/BrowserResize',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserResizeRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BrowserClick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/BrowserClick',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserClickRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BrowserType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/BrowserType',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserTypeRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BrowserWait(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.node.sandbox.v1.NodeSandbox/BrowserWait',
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserWaitRequest.SerializeToString,
            axern_dot_node_dot_sandbox_dot_v1_dot_node__pb2.BrowserStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
