# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: axern/control/service/v1/service_event.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'axern/control/service/v1/service_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from axern.control.service.v1 import service_types_pb2 as axern_dot_control_dot_service_dot_v1_dot_service__types__pb2
from axern.control.common.v1 import common_pb2 as axern_dot_control_dot_common_dot_v1_dot_common__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,axern/control/service/v1/service_event.proto\x12\x18\x61xern.control.service.v1\x1a,axern/control/service/v1/service_types.proto\x1a$axern/control/common/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc5\x02\n\x0cServiceEvent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nservice_id\x18\x02 \x01(\t\x12\x12\n\nreplica_id\x18\x03 \x01(\t\x12\x38\n\x04type\x18\x04 \x01(\x0e\x32*.axern.control.service.v1.ServiceEventType\x12<\n\x05phase\x18\x05 \x01(\x0e\x32-.axern.control.service.v1.ServiceRolloutPhase\x12H\n\x0f\x64iagnostic_code\x18\x06 \x01(\x0e\x32/.axern.control.common.v1.WorkloadDiagnosticCode\x12\x0f\n\x07message\x18\x07 \x01(\t\x12.\n\ncreated_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"=\n\x18ListServiceEventsRequest\x12\x12\n\nservice_id\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"S\n\x19ListServiceEventsResponse\x12\x36\n\x06\x65vents\x18\x01 \x03(\x0b\x32&.axern.control.service.v1.ServiceEvent*\x8e\x05\n\x10ServiceEventType\x12\"\n\x1eSERVICE_EVENT_TYPE_UNSPECIFIED\x10\x00\x12&\n\"SERVICE_EVENT_TYPE_ROLLOUT_STARTED\x10\x01\x12+\n\'SERVICE_EVENT_TYPE_REPLACEMENT_ADMITTED\x10\x02\x12*\n&SERVICE_EVENT_TYPE_REPLACEMENT_BLOCKED\x10\x03\x12*\n&SERVICE_EVENT_TYPE_REPLACEMENT_RUNNING\x10\x04\x12\'\n#SERVICE_EVENT_TYPE_OUTDATED_DRAINED\x10\x05\x12\'\n#SERVICE_EVENT_TYPE_SERVICE_DEGRADED\x10\x06\x12(\n$SERVICE_EVENT_TYPE_SERVICE_RECOVERED\x10\x07\x12(\n$SERVICE_EVENT_TYPE_REPLACEMENT_READY\x10\x08\x12&\n\"SERVICE_EVENT_TYPE_LIVENESS_FAILED\x10\t\x12/\n+SERVICE_EVENT_TYPE_AUTOSCALE_TARGET_CHANGED\x10\n\x12)\n%SERVICE_EVENT_TYPE_DELETION_REQUESTED\x10\x0b\x12+\n\'SERVICE_EVENT_TYPE_VOLUME_RECLAIM_RETRY\x10\x0c\x12\'\n#SERVICE_EVENT_TYPE_VOLUME_RECLAIMED\x10\r\x12)\n%SERVICE_EVENT_TYPE_DELETION_COMPLETED\x10\x0e\x42GZEgithub.com/cofy-x/axern/sdk/go/gen/axern/control/service/v1;servicev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'axern.control.service.v1.service_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZEgithub.com/cofy-x/axern/sdk/go/gen/axern/control/service/v1;servicev1'
  _globals['_SERVICEEVENTTYPE']._serialized_start=668
  _globals['_SERVICEEVENTTYPE']._serialized_end=1322
  _globals['_SERVICEEVENT']._serialized_start=192
  _globals['_SERVICEEVENT']._serialized_end=517
  _globals['_LISTSERVICEEVENTSREQUEST']._serialized_start=519
  _globals['_LISTSERVICEEVENTSREQUEST']._serialized_end=580
  _globals['_LISTSERVICEEVENTSRESPONSE']._serialized_start=582
  _globals['_LISTSERVICEEVENTSRESPONSE']._serialized_end=665
# @@protoc_insertion_point(module_scope)
