// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: internal/apipb/v1/axnoded_internal.proto

package apipb

import (
	v1 "github.com/cofy-x/axern/sdk/go/gen/axern/control/catalog/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RootfsSrcType int32

const (
	RootfsSrcType_S3    RootfsSrcType = 0
	RootfsSrcType_IMAGE RootfsSrcType = 1
	RootfsSrcType_LOCAL RootfsSrcType = 2
)

// Enum value maps for RootfsSrcType.
var (
	RootfsSrcType_name = map[int32]string{
		0: "S3",
		1: "IMAGE",
		2: "LOCAL",
	}
	RootfsSrcType_value = map[string]int32{
		"S3":    0,
		"IMAGE": 1,
		"LOCAL": 2,
	}
)

func (x RootfsSrcType) Enum() *RootfsSrcType {
	p := new(RootfsSrcType)
	*p = x
	return p
}

func (x RootfsSrcType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RootfsSrcType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_apipb_v1_axnoded_internal_proto_enumTypes[0].Descriptor()
}

func (RootfsSrcType) Type() protoreflect.EnumType {
	return &file_internal_apipb_v1_axnoded_internal_proto_enumTypes[0]
}

func (x RootfsSrcType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RootfsSrcType.Descriptor instead.
func (RootfsSrcType) EnumDescriptor() ([]byte, []int) {
	return file_internal_apipb_v1_axnoded_internal_proto_rawDescGZIP(), []int{0}
}

type TaskAssetKind int32

const (
	TaskAssetKind_TASK_ASSET_KIND_UNSPECIFIED TaskAssetKind = 0
	TaskAssetKind_TASK_ASSET_KIND_VERIFIER    TaskAssetKind = 1
	TaskAssetKind_TASK_ASSET_KIND_ORACLE      TaskAssetKind = 2
)

// Enum value maps for TaskAssetKind.
var (
	TaskAssetKind_name = map[int32]string{
		0: "TASK_ASSET_KIND_UNSPECIFIED",
		1: "TASK_ASSET_KIND_VERIFIER",
		2: "TASK_ASSET_KIND_ORACLE",
	}
	TaskAssetKind_value = map[string]int32{
		"TASK_ASSET_KIND_UNSPECIFIED": 0,
		"TASK_ASSET_KIND_VERIFIER":    1,
		"TASK_ASSET_KIND_ORACLE":      2,
	}
)

func (x TaskAssetKind) Enum() *TaskAssetKind {
	p := new(TaskAssetKind)
	*p = x
	return p
}

func (x TaskAssetKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskAssetKind) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_apipb_v1_axnoded_internal_proto_enumTypes[1].Descriptor()
}

func (TaskAssetKind) Type() protoreflect.EnumType {
	return &file_internal_apipb_v1_axnoded_internal_proto_enumTypes[1]
}

func (x TaskAssetKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskAssetKind.Descriptor instead.
func (TaskAssetKind) EnumDescriptor() ([]byte, []int) {
	return file_internal_apipb_v1_axnoded_internal_proto_rawDescGZIP(), []int{1}
}

type S3Config struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Endpoint        string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Bucket          string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Object          string                 `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	AccessKeyID     string                 `protobuf:"bytes,4,opt,name=accessKeyID,proto3" json:"accessKeyID,omitempty"`
	AccessKeySecret string                 `protobuf:"bytes,5,opt,name=access_key_secret,json=accessKeySecret,proto3" json:"access_key_secret,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *S3Config) Reset() {
	*x = S3Config{}
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S3Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S3Config) ProtoMessage() {}

func (x *S3Config) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S3Config.ProtoReflect.Descriptor instead.
func (*S3Config) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_axnoded_internal_proto_rawDescGZIP(), []int{0}
}

func (x *S3Config) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *S3Config) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *S3Config) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *S3Config) GetAccessKeyID() string {
	if x != nil {
		return x.AccessKeyID
	}
	return ""
}

func (x *S3Config) GetAccessKeySecret() string {
	if x != nil {
		return x.AccessKeySecret
	}
	return ""
}

type RootfsConfig struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Readonly bool                   `protobuf:"varint,1,opt,name=readonly,proto3" json:"readonly,omitempty"`
	Type     RootfsSrcType          `protobuf:"varint,2,opt,name=type,proto3,enum=axnoded.internal.apipb.v1.RootfsSrcType" json:"type,omitempty"`
	// Types that are valid to be assigned to Source:
	//
	//	*RootfsConfig_ImageUrl
	//	*RootfsConfig_S3Config
	//	*RootfsConfig_Path
	Source        isRootfsConfig_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootfsConfig) Reset() {
	*x = RootfsConfig{}
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootfsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootfsConfig) ProtoMessage() {}

func (x *RootfsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootfsConfig.ProtoReflect.Descriptor instead.
func (*RootfsConfig) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_axnoded_internal_proto_rawDescGZIP(), []int{1}
}

func (x *RootfsConfig) GetReadonly() bool {
	if x != nil {
		return x.Readonly
	}
	return false
}

func (x *RootfsConfig) GetType() RootfsSrcType {
	if x != nil {
		return x.Type
	}
	return RootfsSrcType_S3
}

func (x *RootfsConfig) GetSource() isRootfsConfig_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *RootfsConfig) GetImageUrl() string {
	if x != nil {
		if x, ok := x.Source.(*RootfsConfig_ImageUrl); ok {
			return x.ImageUrl
		}
	}
	return ""
}

func (x *RootfsConfig) GetS3Config() *S3Config {
	if x != nil {
		if x, ok := x.Source.(*RootfsConfig_S3Config); ok {
			return x.S3Config
		}
	}
	return nil
}

func (x *RootfsConfig) GetPath() string {
	if x != nil {
		if x, ok := x.Source.(*RootfsConfig_Path); ok {
			return x.Path
		}
	}
	return ""
}

type isRootfsConfig_Source interface {
	isRootfsConfig_Source()
}

type RootfsConfig_ImageUrl struct {
	ImageUrl string `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3,oneof"`
}

type RootfsConfig_S3Config struct {
	S3Config *S3Config `protobuf:"bytes,4,opt,name=s3_config,json=s3Config,proto3,oneof"`
}

type RootfsConfig_Path struct {
	Path string `protobuf:"bytes,5,opt,name=path,proto3,oneof"`
}

func (*RootfsConfig_ImageUrl) isRootfsConfig_Source() {}

func (*RootfsConfig_S3Config) isRootfsConfig_Source() {}

func (*RootfsConfig_Path) isRootfsConfig_Source() {}

type Mount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Options       []string               `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mount) Reset() {
	*x = Mount{}
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mount) ProtoMessage() {}

func (x *Mount) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mount.ProtoReflect.Descriptor instead.
func (*Mount) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_axnoded_internal_proto_rawDescGZIP(), []int{2}
}

func (x *Mount) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Mount) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Mount) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Mount) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

type ImageMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Readonly      bool                   `protobuf:"varint,3,opt,name=readonly,proto3" json:"readonly,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageMount) Reset() {
	*x = ImageMount{}
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageMount) ProtoMessage() {}

func (x *ImageMount) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageMount.ProtoReflect.Descriptor instead.
func (*ImageMount) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_axnoded_internal_proto_rawDescGZIP(), []int{3}
}

func (x *ImageMount) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ImageMount) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ImageMount) GetReadonly() bool {
	if x != nil {
		return x.Readonly
	}
	return false
}

type WorkspaceImageVariant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        string                 `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceImageVariant) Reset() {
	*x = WorkspaceImageVariant{}
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceImageVariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceImageVariant) ProtoMessage() {}

func (x *WorkspaceImageVariant) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceImageVariant.ProtoReflect.Descriptor instead.
func (*WorkspaceImageVariant) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_axnoded_internal_proto_rawDescGZIP(), []int{4}
}

func (x *WorkspaceImageVariant) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *WorkspaceImageVariant) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type WorkspaceImageSource struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Variants      []*WorkspaceImageVariant `protobuf:"bytes,1,rep,name=variants,proto3" json:"variants,omitempty"`
	SourcePath    string                   `protobuf:"bytes,2,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	Target        string                   `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceImageSource) Reset() {
	*x = WorkspaceImageSource{}
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceImageSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceImageSource) ProtoMessage() {}

func (x *WorkspaceImageSource) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceImageSource.ProtoReflect.Descriptor instead.
func (*WorkspaceImageSource) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_axnoded_internal_proto_rawDescGZIP(), []int{5}
}

func (x *WorkspaceImageSource) GetVariants() []*WorkspaceImageVariant {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *WorkspaceImageSource) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *WorkspaceImageSource) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type MaterializeTaskAssetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	SourcePath    string                 `protobuf:"bytes,2,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	Target        string                 `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Kind          TaskAssetKind          `protobuf:"varint,4,opt,name=kind,proto3,enum=axnoded.internal.apipb.v1.TaskAssetKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaterializeTaskAssetsRequest) Reset() {
	*x = MaterializeTaskAssetsRequest{}
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterializeTaskAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterializeTaskAssetsRequest) ProtoMessage() {}

func (x *MaterializeTaskAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterializeTaskAssetsRequest.ProtoReflect.Descriptor instead.
func (*MaterializeTaskAssetsRequest) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_axnoded_internal_proto_rawDescGZIP(), []int{6}
}

func (x *MaterializeTaskAssetsRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *MaterializeTaskAssetsRequest) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *MaterializeTaskAssetsRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *MaterializeTaskAssetsRequest) GetKind() TaskAssetKind {
	if x != nil {
		return x.Kind
	}
	return TaskAssetKind_TASK_ASSET_KIND_UNSPECIFIED
}

type MaterializeTaskAssetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DurationMs    int64                  `protobuf:"varint,1,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaterializeTaskAssetsResponse) Reset() {
	*x = MaterializeTaskAssetsResponse{}
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterializeTaskAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterializeTaskAssetsResponse) ProtoMessage() {}

func (x *MaterializeTaskAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterializeTaskAssetsResponse.ProtoReflect.Descriptor instead.
func (*MaterializeTaskAssetsResponse) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_axnoded_internal_proto_rawDescGZIP(), []int{7}
}

func (x *MaterializeTaskAssetsResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type RuntimeTemplate struct {
	state            protoimpl.MessageState      `protogen:"open.v1"`
	ID               string                      `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Sandbox          string                      `protobuf:"bytes,2,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	Rootfs           *RootfsConfig               `protobuf:"bytes,3,opt,name=rootfs,proto3" json:"rootfs,omitempty"`
	Command          []string                    `protobuf:"bytes,4,rep,name=command,proto3" json:"command,omitempty"`
	RuntimeEnvs      map[string]string           `protobuf:"bytes,5,rep,name=runtimeEnvs,proto3" json:"runtimeEnvs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Cwd              string                      `protobuf:"bytes,6,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Mounts           []*Mount                    `protobuf:"bytes,7,rep,name=mounts,proto3" json:"mounts,omitempty"`
	ExecutionProfile *v1.RuntimeExecutionProfile `protobuf:"bytes,8,opt,name=execution_profile,json=executionProfile,proto3" json:"execution_profile,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RuntimeTemplate) Reset() {
	*x = RuntimeTemplate{}
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeTemplate) ProtoMessage() {}

func (x *RuntimeTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeTemplate.ProtoReflect.Descriptor instead.
func (*RuntimeTemplate) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_axnoded_internal_proto_rawDescGZIP(), []int{8}
}

func (x *RuntimeTemplate) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *RuntimeTemplate) GetSandbox() string {
	if x != nil {
		return x.Sandbox
	}
	return ""
}

func (x *RuntimeTemplate) GetRootfs() *RootfsConfig {
	if x != nil {
		return x.Rootfs
	}
	return nil
}

func (x *RuntimeTemplate) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *RuntimeTemplate) GetRuntimeEnvs() map[string]string {
	if x != nil {
		return x.RuntimeEnvs
	}
	return nil
}

func (x *RuntimeTemplate) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *RuntimeTemplate) GetMounts() []*Mount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *RuntimeTemplate) GetExecutionProfile() *v1.RuntimeExecutionProfile {
	if x != nil {
		return x.ExecutionProfile
	}
	return nil
}

type AllocationState struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AllocationID        string                 `protobuf:"bytes,1,opt,name=allocationID,proto3" json:"allocationID,omitempty"`
	RuntimeTemplate     *RuntimeTemplate       `protobuf:"bytes,2,opt,name=runtime_template,json=runtimeTemplate,proto3" json:"runtime_template,omitempty"`
	ImageMountUrls      []string               `protobuf:"bytes,3,rep,name=image_mount_urls,json=imageMountUrls,proto3" json:"image_mount_urls,omitempty"`
	WorkspaceImageUrl   string                 `protobuf:"bytes,4,opt,name=workspace_image_url,json=workspaceImageUrl,proto3" json:"workspace_image_url,omitempty"`
	WorkspaceSourcePath string                 `protobuf:"bytes,5,opt,name=workspace_source_path,json=workspaceSourcePath,proto3" json:"workspace_source_path,omitempty"`
	WorkspaceTarget     string                 `protobuf:"bytes,6,opt,name=workspace_target,json=workspaceTarget,proto3" json:"workspace_target,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AllocationState) Reset() {
	*x = AllocationState{}
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocationState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocationState) ProtoMessage() {}

func (x *AllocationState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocationState.ProtoReflect.Descriptor instead.
func (*AllocationState) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_axnoded_internal_proto_rawDescGZIP(), []int{9}
}

func (x *AllocationState) GetAllocationID() string {
	if x != nil {
		return x.AllocationID
	}
	return ""
}

func (x *AllocationState) GetRuntimeTemplate() *RuntimeTemplate {
	if x != nil {
		return x.RuntimeTemplate
	}
	return nil
}

func (x *AllocationState) GetImageMountUrls() []string {
	if x != nil {
		return x.ImageMountUrls
	}
	return nil
}

func (x *AllocationState) GetWorkspaceImageUrl() string {
	if x != nil {
		return x.WorkspaceImageUrl
	}
	return ""
}

func (x *AllocationState) GetWorkspaceSourcePath() string {
	if x != nil {
		return x.WorkspaceSourcePath
	}
	return ""
}

func (x *AllocationState) GetWorkspaceTarget() string {
	if x != nil {
		return x.WorkspaceTarget
	}
	return ""
}

type TerminalResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalResize) Reset() {
	*x = TerminalResize{}
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalResize) ProtoMessage() {}

func (x *TerminalResize) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalResize.ProtoReflect.Descriptor instead.
func (*TerminalResize) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_axnoded_internal_proto_rawDescGZIP(), []int{10}
}

func (x *TerminalResize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *TerminalResize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_axnoded_internal_proto_rawDescGZIP(), []int{11}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type LinuxContainerResources struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	CpuPeriod              uint64                 `protobuf:"varint,1,opt,name=cpu_period,json=cpuPeriod,proto3" json:"cpu_period,omitempty"`
	CpuQuota               int64                  `protobuf:"varint,2,opt,name=cpu_quota,json=cpuQuota,proto3" json:"cpu_quota,omitempty"`
	CpuShares              uint64                 `protobuf:"varint,3,opt,name=cpu_shares,json=cpuShares,proto3" json:"cpu_shares,omitempty"`
	MemoryLimitInBytes     int64                  `protobuf:"varint,4,opt,name=memory_limit_in_bytes,json=memoryLimitInBytes,proto3" json:"memory_limit_in_bytes,omitempty"`
	OomScoreAdj            int64                  `protobuf:"varint,5,opt,name=oom_score_adj,json=oomScoreAdj,proto3" json:"oom_score_adj,omitempty"`
	CpusetCpus             string                 `protobuf:"bytes,6,opt,name=cpuset_cpus,json=cpusetCpus,proto3" json:"cpuset_cpus,omitempty"`
	CpusetMems             string                 `protobuf:"bytes,7,opt,name=cpuset_mems,json=cpusetMems,proto3" json:"cpuset_mems,omitempty"`
	HugepageLimits         []*HugepageLimit       `protobuf:"bytes,8,rep,name=hugepage_limits,json=hugepageLimits,proto3" json:"hugepage_limits,omitempty"`
	Unified                map[string]string      `protobuf:"bytes,9,rep,name=unified,proto3" json:"unified,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MemorySwapLimitInBytes int64                  `protobuf:"varint,10,opt,name=memory_swap_limit_in_bytes,json=memorySwapLimitInBytes,proto3" json:"memory_swap_limit_in_bytes,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LinuxContainerResources) Reset() {
	*x = LinuxContainerResources{}
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinuxContainerResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinuxContainerResources) ProtoMessage() {}

func (x *LinuxContainerResources) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinuxContainerResources.ProtoReflect.Descriptor instead.
func (*LinuxContainerResources) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_axnoded_internal_proto_rawDescGZIP(), []int{12}
}

func (x *LinuxContainerResources) GetCpuPeriod() uint64 {
	if x != nil {
		return x.CpuPeriod
	}
	return 0
}

func (x *LinuxContainerResources) GetCpuQuota() int64 {
	if x != nil {
		return x.CpuQuota
	}
	return 0
}

func (x *LinuxContainerResources) GetCpuShares() uint64 {
	if x != nil {
		return x.CpuShares
	}
	return 0
}

func (x *LinuxContainerResources) GetMemoryLimitInBytes() int64 {
	if x != nil {
		return x.MemoryLimitInBytes
	}
	return 0
}

func (x *LinuxContainerResources) GetOomScoreAdj() int64 {
	if x != nil {
		return x.OomScoreAdj
	}
	return 0
}

func (x *LinuxContainerResources) GetCpusetCpus() string {
	if x != nil {
		return x.CpusetCpus
	}
	return ""
}

func (x *LinuxContainerResources) GetCpusetMems() string {
	if x != nil {
		return x.CpusetMems
	}
	return ""
}

func (x *LinuxContainerResources) GetHugepageLimits() []*HugepageLimit {
	if x != nil {
		return x.HugepageLimits
	}
	return nil
}

func (x *LinuxContainerResources) GetUnified() map[string]string {
	if x != nil {
		return x.Unified
	}
	return nil
}

func (x *LinuxContainerResources) GetMemorySwapLimitInBytes() int64 {
	if x != nil {
		return x.MemorySwapLimitInBytes
	}
	return 0
}

type HugepageLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      string                 `protobuf:"bytes,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HugepageLimit) Reset() {
	*x = HugepageLimit{}
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HugepageLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HugepageLimit) ProtoMessage() {}

func (x *HugepageLimit) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HugepageLimit.ProtoReflect.Descriptor instead.
func (*HugepageLimit) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_axnoded_internal_proto_rawDescGZIP(), []int{13}
}

func (x *HugepageLimit) GetPageSize() string {
	if x != nil {
		return x.PageSize
	}
	return ""
}

func (x *HugepageLimit) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Rootfs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	LowerDir      string                 `protobuf:"bytes,2,opt,name=lower_dir,json=lowerDir,proto3" json:"lower_dir,omitempty"`
	RootDir       string                 `protobuf:"bytes,3,opt,name=root_dir,json=rootDir,proto3" json:"root_dir,omitempty"`
	Readonly      bool                   `protobuf:"varint,4,opt,name=readonly,proto3" json:"readonly,omitempty"`
	LeaseId       string                 `protobuf:"bytes,5,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rootfs) Reset() {
	*x = Rootfs{}
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rootfs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rootfs) ProtoMessage() {}

func (x *Rootfs) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rootfs.ProtoReflect.Descriptor instead.
func (*Rootfs) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_axnoded_internal_proto_rawDescGZIP(), []int{14}
}

func (x *Rootfs) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Rootfs) GetLowerDir() string {
	if x != nil {
		return x.LowerDir
	}
	return ""
}

func (x *Rootfs) GetRootDir() string {
	if x != nil {
		return x.RootDir
	}
	return ""
}

func (x *Rootfs) GetReadonly() bool {
	if x != nil {
		return x.Readonly
	}
	return false
}

func (x *Rootfs) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

type ContainerMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ID             string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	RuntimeHandler string                 `protobuf:"bytes,3,opt,name=runtime_handler,json=runtimeHandler,proto3" json:"runtime_handler,omitempty"`
	Labels         map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Stdout         string                 `protobuf:"bytes,6,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr         string                 `protobuf:"bytes,7,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ContainerMetadata) Reset() {
	*x = ContainerMetadata{}
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerMetadata) ProtoMessage() {}

func (x *ContainerMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerMetadata.ProtoReflect.Descriptor instead.
func (*ContainerMetadata) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_axnoded_internal_proto_rawDescGZIP(), []int{15}
}

func (x *ContainerMetadata) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ContainerMetadata) GetRuntimeHandler() string {
	if x != nil {
		return x.RuntimeHandler
	}
	return ""
}

func (x *ContainerMetadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ContainerMetadata) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ContainerMetadata) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

type ContainerMetadataList struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Containers    map[string]*ContainerMetadata `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerMetadataList) Reset() {
	*x = ContainerMetadataList{}
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerMetadataList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerMetadataList) ProtoMessage() {}

func (x *ContainerMetadataList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerMetadataList.ProtoReflect.Descriptor instead.
func (*ContainerMetadataList) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_axnoded_internal_proto_rawDescGZIP(), []int{16}
}

func (x *ContainerMetadataList) GetContainers() map[string]*ContainerMetadata {
	if x != nil {
		return x.Containers
	}
	return nil
}

type Slice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []string               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Slice) Reset() {
	*x = Slice{}
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slice) ProtoMessage() {}

func (x *Slice) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slice.ProtoReflect.Descriptor instead.
func (*Slice) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_axnoded_internal_proto_rawDescGZIP(), []int{17}
}

func (x *Slice) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

type Map struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         map[string]string      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Map) Reset() {
	*x = Map{}
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Map) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Map) ProtoMessage() {}

func (x *Map) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_axnoded_internal_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Map.ProtoReflect.Descriptor instead.
func (*Map) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_axnoded_internal_proto_rawDescGZIP(), []int{18}
}

func (x *Map) GetItems() map[string]string {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_internal_apipb_v1_axnoded_internal_proto protoreflect.FileDescriptor

const file_internal_apipb_v1_axnoded_internal_proto_rawDesc = "" +
	"\n" +
	"(internal/apipb/v1/axnoded_internal.proto\x12\x19axnoded.internal.apipb.v1\x1a&axern/control/catalog/v1/catalog.proto\"\xa4\x01\n" +
	"\bS3Config\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x16\n" +
	"\x06object\x18\x03 \x01(\tR\x06object\x12 \n" +
	"\vaccessKeyID\x18\x04 \x01(\tR\vaccessKeyID\x12*\n" +
	"\x11access_key_secret\x18\x05 \x01(\tR\x0faccessKeySecret\"\xeb\x01\n" +
	"\fRootfsConfig\x12\x1a\n" +
	"\breadonly\x18\x01 \x01(\bR\breadonly\x12<\n" +
	"\x04type\x18\x02 \x01(\x0e2(.axnoded.internal.apipb.v1.RootfsSrcTypeR\x04type\x12\x1d\n" +
	"\timage_url\x18\x03 \x01(\tH\x00R\bimageUrl\x12B\n" +
	"\ts3_config\x18\x04 \x01(\v2#.axnoded.internal.apipb.v1.S3ConfigH\x00R\bs3Config\x12\x14\n" +
	"\x04path\x18\x05 \x01(\tH\x00R\x04pathB\b\n" +
	"\x06source\"e\n" +
	"\x05Mount\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12\x18\n" +
	"\aoptions\x18\x04 \x03(\tR\aoptions\"V\n" +
	"\n" +
	"ImageMount\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1a\n" +
	"\breadonly\x18\x03 \x01(\bR\breadonly\"E\n" +
	"\x15WorkspaceImageVariant\x12\x16\n" +
	"\x06format\x18\x01 \x01(\tR\x06format\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\"\x9d\x01\n" +
	"\x14WorkspaceImageSource\x12L\n" +
	"\bvariants\x18\x01 \x03(\v20.axnoded.internal.apipb.v1.WorkspaceImageVariantR\bvariants\x12\x1f\n" +
	"\vsource_path\x18\x02 \x01(\tR\n" +
	"sourcePath\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\"\xa5\x01\n" +
	"\x1cMaterializeTaskAssetsRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1f\n" +
	"\vsource_path\x18\x02 \x01(\tR\n" +
	"sourcePath\x12\x16\n" +
	"\x06target\x18\x03 \x01(\tR\x06target\x12<\n" +
	"\x04kind\x18\x04 \x01(\x0e2(.axnoded.internal.apipb.v1.TaskAssetKindR\x04kind\"@\n" +
	"\x1dMaterializeTaskAssetsResponse\x12\x1f\n" +
	"\vduration_ms\x18\x01 \x01(\x03R\n" +
	"durationMs\"\xe1\x03\n" +
	"\x0fRuntimeTemplate\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x18\n" +
	"\asandbox\x18\x02 \x01(\tR\asandbox\x12?\n" +
	"\x06rootfs\x18\x03 \x01(\v2'.axnoded.internal.apipb.v1.RootfsConfigR\x06rootfs\x12\x18\n" +
	"\acommand\x18\x04 \x03(\tR\acommand\x12]\n" +
	"\vruntimeEnvs\x18\x05 \x03(\v2;.axnoded.internal.apipb.v1.RuntimeTemplate.RuntimeEnvsEntryR\vruntimeEnvs\x12\x10\n" +
	"\x03cwd\x18\x06 \x01(\tR\x03cwd\x128\n" +
	"\x06mounts\x18\a \x03(\v2 .axnoded.internal.apipb.v1.MountR\x06mounts\x12^\n" +
	"\x11execution_profile\x18\b \x01(\v21.axern.control.catalog.v1.RuntimeExecutionProfileR\x10executionProfile\x1a>\n" +
	"\x10RuntimeEnvsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc5\x02\n" +
	"\x0fAllocationState\x12\"\n" +
	"\fallocationID\x18\x01 \x01(\tR\fallocationID\x12U\n" +
	"\x10runtime_template\x18\x02 \x01(\v2*.axnoded.internal.apipb.v1.RuntimeTemplateR\x0fruntimeTemplate\x12(\n" +
	"\x10image_mount_urls\x18\x03 \x03(\tR\x0eimageMountUrls\x12.\n" +
	"\x13workspace_image_url\x18\x04 \x01(\tR\x11workspaceImageUrl\x122\n" +
	"\x15workspace_source_path\x18\x05 \x01(\tR\x13workspaceSourcePath\x12)\n" +
	"\x10workspace_target\x18\x06 \x01(\tR\x0fworkspaceTarget\"8\n" +
	"\x0eTerminalResize\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\"2\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xb3\x04\n" +
	"\x17LinuxContainerResources\x12\x1d\n" +
	"\n" +
	"cpu_period\x18\x01 \x01(\x04R\tcpuPeriod\x12\x1b\n" +
	"\tcpu_quota\x18\x02 \x01(\x03R\bcpuQuota\x12\x1d\n" +
	"\n" +
	"cpu_shares\x18\x03 \x01(\x04R\tcpuShares\x121\n" +
	"\x15memory_limit_in_bytes\x18\x04 \x01(\x03R\x12memoryLimitInBytes\x12\"\n" +
	"\room_score_adj\x18\x05 \x01(\x03R\voomScoreAdj\x12\x1f\n" +
	"\vcpuset_cpus\x18\x06 \x01(\tR\n" +
	"cpusetCpus\x12\x1f\n" +
	"\vcpuset_mems\x18\a \x01(\tR\n" +
	"cpusetMems\x12Q\n" +
	"\x0fhugepage_limits\x18\b \x03(\v2(.axnoded.internal.apipb.v1.HugepageLimitR\x0ehugepageLimits\x12Y\n" +
	"\aunified\x18\t \x03(\v2?.axnoded.internal.apipb.v1.LinuxContainerResources.UnifiedEntryR\aunified\x12:\n" +
	"\x1amemory_swap_limit_in_bytes\x18\n" +
	" \x01(\x03R\x16memorySwapLimitInBytes\x1a:\n" +
	"\fUnifiedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\rHugepageLimit\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\tR\bpageSize\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\"\x8b\x01\n" +
	"\x06Rootfs\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\tlower_dir\x18\x02 \x01(\tR\blowerDir\x12\x19\n" +
	"\broot_dir\x18\x03 \x01(\tR\arootDir\x12\x1a\n" +
	"\breadonly\x18\x04 \x01(\bR\breadonly\x12\x19\n" +
	"\blease_id\x18\x05 \x01(\tR\aleaseId\"\x89\x02\n" +
	"\x11ContainerMetadata\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12'\n" +
	"\x0fruntime_handler\x18\x03 \x01(\tR\x0eruntimeHandler\x12P\n" +
	"\x06labels\x18\x04 \x03(\v28.axnoded.internal.apipb.v1.ContainerMetadata.LabelsEntryR\x06labels\x12\x16\n" +
	"\x06stdout\x18\x06 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\a \x01(\tR\x06stderr\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe6\x01\n" +
	"\x15ContainerMetadataList\x12`\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2@.axnoded.internal.apipb.v1.ContainerMetadataList.ContainersEntryR\n" +
	"containers\x1ak\n" +
	"\x0fContainersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12B\n" +
	"\x05value\x18\x02 \x01(\v2,.axnoded.internal.apipb.v1.ContainerMetadataR\x05value:\x028\x01\"\x1d\n" +
	"\x05Slice\x12\x14\n" +
	"\x05items\x18\x01 \x03(\tR\x05items\"\x80\x01\n" +
	"\x03Map\x12?\n" +
	"\x05items\x18\x01 \x03(\v2).axnoded.internal.apipb.v1.Map.ItemsEntryR\x05items\x1a8\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*-\n" +
	"\rRootfsSrcType\x12\x06\n" +
	"\x02S3\x10\x00\x12\t\n" +
	"\x05IMAGE\x10\x01\x12\t\n" +
	"\x05LOCAL\x10\x02*j\n" +
	"\rTaskAssetKind\x12\x1f\n" +
	"\x1bTASK_ASSET_KIND_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18TASK_ASSET_KIND_VERIFIER\x10\x01\x12\x1a\n" +
	"\x16TASK_ASSET_KIND_ORACLE\x10\x02BAZ?github.com/cofy-x/axern/runtime/axnoded/internal/apipb/v1;apipbb\x06proto3"

var (
	file_internal_apipb_v1_axnoded_internal_proto_rawDescOnce sync.Once
	file_internal_apipb_v1_axnoded_internal_proto_rawDescData []byte
)

func file_internal_apipb_v1_axnoded_internal_proto_rawDescGZIP() []byte {
	file_internal_apipb_v1_axnoded_internal_proto_rawDescOnce.Do(func() {
		file_internal_apipb_v1_axnoded_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_apipb_v1_axnoded_internal_proto_rawDesc), len(file_internal_apipb_v1_axnoded_internal_proto_rawDesc)))
	})
	return file_internal_apipb_v1_axnoded_internal_proto_rawDescData
}

var file_internal_apipb_v1_axnoded_internal_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_apipb_v1_axnoded_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_internal_apipb_v1_axnoded_internal_proto_goTypes = []any{
	(RootfsSrcType)(0),                    // 0: axnoded.internal.apipb.v1.RootfsSrcType
	(TaskAssetKind)(0),                    // 1: axnoded.internal.apipb.v1.TaskAssetKind
	(*S3Config)(nil),                      // 2: axnoded.internal.apipb.v1.S3Config
	(*RootfsConfig)(nil),                  // 3: axnoded.internal.apipb.v1.RootfsConfig
	(*Mount)(nil),                         // 4: axnoded.internal.apipb.v1.Mount
	(*ImageMount)(nil),                    // 5: axnoded.internal.apipb.v1.ImageMount
	(*WorkspaceImageVariant)(nil),         // 6: axnoded.internal.apipb.v1.WorkspaceImageVariant
	(*WorkspaceImageSource)(nil),          // 7: axnoded.internal.apipb.v1.WorkspaceImageSource
	(*MaterializeTaskAssetsRequest)(nil),  // 8: axnoded.internal.apipb.v1.MaterializeTaskAssetsRequest
	(*MaterializeTaskAssetsResponse)(nil), // 9: axnoded.internal.apipb.v1.MaterializeTaskAssetsResponse
	(*RuntimeTemplate)(nil),               // 10: axnoded.internal.apipb.v1.RuntimeTemplate
	(*AllocationState)(nil),               // 11: axnoded.internal.apipb.v1.AllocationState
	(*TerminalResize)(nil),                // 12: axnoded.internal.apipb.v1.TerminalResize
	(*KeyValue)(nil),                      // 13: axnoded.internal.apipb.v1.KeyValue
	(*LinuxContainerResources)(nil),       // 14: axnoded.internal.apipb.v1.LinuxContainerResources
	(*HugepageLimit)(nil),                 // 15: axnoded.internal.apipb.v1.HugepageLimit
	(*Rootfs)(nil),                        // 16: axnoded.internal.apipb.v1.Rootfs
	(*ContainerMetadata)(nil),             // 17: axnoded.internal.apipb.v1.ContainerMetadata
	(*ContainerMetadataList)(nil),         // 18: axnoded.internal.apipb.v1.ContainerMetadataList
	(*Slice)(nil),                         // 19: axnoded.internal.apipb.v1.Slice
	(*Map)(nil),                           // 20: axnoded.internal.apipb.v1.Map
	nil,                                   // 21: axnoded.internal.apipb.v1.RuntimeTemplate.RuntimeEnvsEntry
	nil,                                   // 22: axnoded.internal.apipb.v1.LinuxContainerResources.UnifiedEntry
	nil,                                   // 23: axnoded.internal.apipb.v1.ContainerMetadata.LabelsEntry
	nil,                                   // 24: axnoded.internal.apipb.v1.ContainerMetadataList.ContainersEntry
	nil,                                   // 25: axnoded.internal.apipb.v1.Map.ItemsEntry
	(*v1.RuntimeExecutionProfile)(nil),    // 26: axern.control.catalog.v1.RuntimeExecutionProfile
}
var file_internal_apipb_v1_axnoded_internal_proto_depIdxs = []int32{
	0,  // 0: axnoded.internal.apipb.v1.RootfsConfig.type:type_name -> axnoded.internal.apipb.v1.RootfsSrcType
	2,  // 1: axnoded.internal.apipb.v1.RootfsConfig.s3_config:type_name -> axnoded.internal.apipb.v1.S3Config
	6,  // 2: axnoded.internal.apipb.v1.WorkspaceImageSource.variants:type_name -> axnoded.internal.apipb.v1.WorkspaceImageVariant
	1,  // 3: axnoded.internal.apipb.v1.MaterializeTaskAssetsRequest.kind:type_name -> axnoded.internal.apipb.v1.TaskAssetKind
	3,  // 4: axnoded.internal.apipb.v1.RuntimeTemplate.rootfs:type_name -> axnoded.internal.apipb.v1.RootfsConfig
	21, // 5: axnoded.internal.apipb.v1.RuntimeTemplate.runtimeEnvs:type_name -> axnoded.internal.apipb.v1.RuntimeTemplate.RuntimeEnvsEntry
	4,  // 6: axnoded.internal.apipb.v1.RuntimeTemplate.mounts:type_name -> axnoded.internal.apipb.v1.Mount
	26, // 7: axnoded.internal.apipb.v1.RuntimeTemplate.execution_profile:type_name -> axern.control.catalog.v1.RuntimeExecutionProfile
	10, // 8: axnoded.internal.apipb.v1.AllocationState.runtime_template:type_name -> axnoded.internal.apipb.v1.RuntimeTemplate
	15, // 9: axnoded.internal.apipb.v1.LinuxContainerResources.hugepage_limits:type_name -> axnoded.internal.apipb.v1.HugepageLimit
	22, // 10: axnoded.internal.apipb.v1.LinuxContainerResources.unified:type_name -> axnoded.internal.apipb.v1.LinuxContainerResources.UnifiedEntry
	23, // 11: axnoded.internal.apipb.v1.ContainerMetadata.labels:type_name -> axnoded.internal.apipb.v1.ContainerMetadata.LabelsEntry
	24, // 12: axnoded.internal.apipb.v1.ContainerMetadataList.containers:type_name -> axnoded.internal.apipb.v1.ContainerMetadataList.ContainersEntry
	25, // 13: axnoded.internal.apipb.v1.Map.items:type_name -> axnoded.internal.apipb.v1.Map.ItemsEntry
	17, // 14: axnoded.internal.apipb.v1.ContainerMetadataList.ContainersEntry.value:type_name -> axnoded.internal.apipb.v1.ContainerMetadata
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_internal_apipb_v1_axnoded_internal_proto_init() }
func file_internal_apipb_v1_axnoded_internal_proto_init() {
	if File_internal_apipb_v1_axnoded_internal_proto != nil {
		return
	}
	file_internal_apipb_v1_axnoded_internal_proto_msgTypes[1].OneofWrappers = []any{
		(*RootfsConfig_ImageUrl)(nil),
		(*RootfsConfig_S3Config)(nil),
		(*RootfsConfig_Path)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_apipb_v1_axnoded_internal_proto_rawDesc), len(file_internal_apipb_v1_axnoded_internal_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_apipb_v1_axnoded_internal_proto_goTypes,
		DependencyIndexes: file_internal_apipb_v1_axnoded_internal_proto_depIdxs,
		EnumInfos:         file_internal_apipb_v1_axnoded_internal_proto_enumTypes,
		MessageInfos:      file_internal_apipb_v1_axnoded_internal_proto_msgTypes,
	}.Build()
	File_internal_apipb_v1_axnoded_internal_proto = out.File
	file_internal_apipb_v1_axnoded_internal_proto_goTypes = nil
	file_internal_apipb_v1_axnoded_internal_proto_depIdxs = nil
}
