// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: internal/apipb/v1/computer_use.proto

package apipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComputerUseStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputerUseStatusRequest) Reset() {
	*x = ComputerUseStatusRequest{}
	mi := &file_internal_apipb_v1_computer_use_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputerUseStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputerUseStatusRequest) ProtoMessage() {}

func (x *ComputerUseStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_computer_use_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputerUseStatusRequest.ProtoReflect.Descriptor instead.
func (*ComputerUseStatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_computer_use_proto_rawDescGZIP(), []int{0}
}

func (x *ComputerUseStatusRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type ComputerUseStatusResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Available     bool                           `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Display       string                         `protobuf:"bytes,2,opt,name=display,proto3" json:"display,omitempty"`
	Backend       string                         `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	Reason        string                         `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Dependencies  []*ComputerUseDependencyStatus `protobuf:"bytes,5,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputerUseStatusResponse) Reset() {
	*x = ComputerUseStatusResponse{}
	mi := &file_internal_apipb_v1_computer_use_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputerUseStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputerUseStatusResponse) ProtoMessage() {}

func (x *ComputerUseStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_computer_use_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputerUseStatusResponse.ProtoReflect.Descriptor instead.
func (*ComputerUseStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_computer_use_proto_rawDescGZIP(), []int{1}
}

func (x *ComputerUseStatusResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *ComputerUseStatusResponse) GetDisplay() string {
	if x != nil {
		return x.Display
	}
	return ""
}

func (x *ComputerUseStatusResponse) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *ComputerUseStatusResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ComputerUseStatusResponse) GetDependencies() []*ComputerUseDependencyStatus {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

type ComputerUseDependencyStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Available     bool                   `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputerUseDependencyStatus) Reset() {
	*x = ComputerUseDependencyStatus{}
	mi := &file_internal_apipb_v1_computer_use_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputerUseDependencyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputerUseDependencyStatus) ProtoMessage() {}

func (x *ComputerUseDependencyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_computer_use_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputerUseDependencyStatus.ProtoReflect.Descriptor instead.
func (*ComputerUseDependencyStatus) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_computer_use_proto_rawDescGZIP(), []int{2}
}

func (x *ComputerUseDependencyStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComputerUseDependencyStatus) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *ComputerUseDependencyStatus) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ComputerUseRegion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputerUseRegion) Reset() {
	*x = ComputerUseRegion{}
	mi := &file_internal_apipb_v1_computer_use_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputerUseRegion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputerUseRegion) ProtoMessage() {}

func (x *ComputerUseRegion) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_computer_use_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputerUseRegion.ProtoReflect.Descriptor instead.
func (*ComputerUseRegion) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_computer_use_proto_rawDescGZIP(), []int{3}
}

func (x *ComputerUseRegion) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ComputerUseRegion) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ComputerUseRegion) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ComputerUseRegion) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type ComputerUseScreenshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ShowCursor    bool                   `protobuf:"varint,2,opt,name=show_cursor,json=showCursor,proto3" json:"show_cursor,omitempty"`
	Region        *ComputerUseRegion     `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	Quality       int32                  `protobuf:"varint,5,opt,name=quality,proto3" json:"quality,omitempty"`
	Scale         float64                `protobuf:"fixed64,6,opt,name=scale,proto3" json:"scale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputerUseScreenshotRequest) Reset() {
	*x = ComputerUseScreenshotRequest{}
	mi := &file_internal_apipb_v1_computer_use_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputerUseScreenshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputerUseScreenshotRequest) ProtoMessage() {}

func (x *ComputerUseScreenshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_computer_use_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputerUseScreenshotRequest.ProtoReflect.Descriptor instead.
func (*ComputerUseScreenshotRequest) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_computer_use_proto_rawDescGZIP(), []int{4}
}

func (x *ComputerUseScreenshotRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ComputerUseScreenshotRequest) GetShowCursor() bool {
	if x != nil {
		return x.ShowCursor
	}
	return false
}

func (x *ComputerUseScreenshotRequest) GetRegion() *ComputerUseRegion {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *ComputerUseScreenshotRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ComputerUseScreenshotRequest) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *ComputerUseScreenshotRequest) GetScale() float64 {
	if x != nil {
		return x.Scale
	}
	return 0
}

type ComputerUseScreenshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputerUseScreenshotResponse) Reset() {
	*x = ComputerUseScreenshotResponse{}
	mi := &file_internal_apipb_v1_computer_use_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputerUseScreenshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputerUseScreenshotResponse) ProtoMessage() {}

func (x *ComputerUseScreenshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_computer_use_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputerUseScreenshotResponse.ProtoReflect.Descriptor instead.
func (*ComputerUseScreenshotResponse) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_computer_use_proto_rawDescGZIP(), []int{5}
}

func (x *ComputerUseScreenshotResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ComputerUseScreenshotResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type ComputerUseDisplayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputerUseDisplayRequest) Reset() {
	*x = ComputerUseDisplayRequest{}
	mi := &file_internal_apipb_v1_computer_use_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputerUseDisplayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputerUseDisplayRequest) ProtoMessage() {}

func (x *ComputerUseDisplayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_computer_use_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputerUseDisplayRequest.ProtoReflect.Descriptor instead.
func (*ComputerUseDisplayRequest) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_computer_use_proto_rawDescGZIP(), []int{6}
}

func (x *ComputerUseDisplayRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type ComputerUseDisplayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Display       string                 `protobuf:"bytes,1,opt,name=display,proto3" json:"display,omitempty"`
	Backend       string                 `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputerUseDisplayResponse) Reset() {
	*x = ComputerUseDisplayResponse{}
	mi := &file_internal_apipb_v1_computer_use_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputerUseDisplayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputerUseDisplayResponse) ProtoMessage() {}

func (x *ComputerUseDisplayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_computer_use_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputerUseDisplayResponse.ProtoReflect.Descriptor instead.
func (*ComputerUseDisplayResponse) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_computer_use_proto_rawDescGZIP(), []int{7}
}

func (x *ComputerUseDisplayResponse) GetDisplay() string {
	if x != nil {
		return x.Display
	}
	return ""
}

func (x *ComputerUseDisplayResponse) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *ComputerUseDisplayResponse) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ComputerUseDisplayResponse) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type ComputerUseMouseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	ToX           int32                  `protobuf:"varint,5,opt,name=to_x,json=toX,proto3" json:"to_x,omitempty"`
	ToY           int32                  `protobuf:"varint,6,opt,name=to_y,json=toY,proto3" json:"to_y,omitempty"`
	Button        string                 `protobuf:"bytes,7,opt,name=button,proto3" json:"button,omitempty"`
	Direction     string                 `protobuf:"bytes,8,opt,name=direction,proto3" json:"direction,omitempty"`
	Amount        int32                  `protobuf:"varint,9,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputerUseMouseRequest) Reset() {
	*x = ComputerUseMouseRequest{}
	mi := &file_internal_apipb_v1_computer_use_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputerUseMouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputerUseMouseRequest) ProtoMessage() {}

func (x *ComputerUseMouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_computer_use_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputerUseMouseRequest.ProtoReflect.Descriptor instead.
func (*ComputerUseMouseRequest) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_computer_use_proto_rawDescGZIP(), []int{8}
}

func (x *ComputerUseMouseRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ComputerUseMouseRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ComputerUseMouseRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ComputerUseMouseRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ComputerUseMouseRequest) GetToX() int32 {
	if x != nil {
		return x.ToX
	}
	return 0
}

func (x *ComputerUseMouseRequest) GetToY() int32 {
	if x != nil {
		return x.ToY
	}
	return 0
}

func (x *ComputerUseMouseRequest) GetButton() string {
	if x != nil {
		return x.Button
	}
	return ""
}

func (x *ComputerUseMouseRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *ComputerUseMouseRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ComputerUseMouseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputerUseMouseResponse) Reset() {
	*x = ComputerUseMouseResponse{}
	mi := &file_internal_apipb_v1_computer_use_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputerUseMouseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputerUseMouseResponse) ProtoMessage() {}

func (x *ComputerUseMouseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_computer_use_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputerUseMouseResponse.ProtoReflect.Descriptor instead.
func (*ComputerUseMouseResponse) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_computer_use_proto_rawDescGZIP(), []int{9}
}

type ComputerUseKeyboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Keys          []string               `protobuf:"bytes,4,rep,name=keys,proto3" json:"keys,omitempty"`
	DelayMs       int32                  `protobuf:"varint,5,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputerUseKeyboardRequest) Reset() {
	*x = ComputerUseKeyboardRequest{}
	mi := &file_internal_apipb_v1_computer_use_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputerUseKeyboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputerUseKeyboardRequest) ProtoMessage() {}

func (x *ComputerUseKeyboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_computer_use_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputerUseKeyboardRequest.ProtoReflect.Descriptor instead.
func (*ComputerUseKeyboardRequest) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_computer_use_proto_rawDescGZIP(), []int{10}
}

func (x *ComputerUseKeyboardRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ComputerUseKeyboardRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ComputerUseKeyboardRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ComputerUseKeyboardRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *ComputerUseKeyboardRequest) GetDelayMs() int32 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

type ComputerUseKeyboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputerUseKeyboardResponse) Reset() {
	*x = ComputerUseKeyboardResponse{}
	mi := &file_internal_apipb_v1_computer_use_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputerUseKeyboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputerUseKeyboardResponse) ProtoMessage() {}

func (x *ComputerUseKeyboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_computer_use_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputerUseKeyboardResponse.ProtoReflect.Descriptor instead.
func (*ComputerUseKeyboardResponse) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_computer_use_proto_rawDescGZIP(), []int{11}
}

var File_internal_apipb_v1_computer_use_proto protoreflect.FileDescriptor

const file_internal_apipb_v1_computer_use_proto_rawDesc = "" +
	"\n" +
	"$internal/apipb/v1/computer_use.proto\x12\x19axnoded.internal.apipb.v1\"*\n" +
	"\x18ComputerUseStatusRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"\xe1\x01\n" +
	"\x19ComputerUseStatusResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x18\n" +
	"\adisplay\x18\x02 \x01(\tR\adisplay\x12\x18\n" +
	"\abackend\x18\x03 \x01(\tR\abackend\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12Z\n" +
	"\fdependencies\x18\x05 \x03(\v26.axnoded.internal.apipb.v1.ComputerUseDependencyStatusR\fdependencies\"g\n" +
	"\x1bComputerUseDependencyStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\bR\tavailable\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"]\n" +
	"\x11ComputerUseRegion\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\"\xdd\x01\n" +
	"\x1cComputerUseScreenshotRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1f\n" +
	"\vshow_cursor\x18\x02 \x01(\bR\n" +
	"showCursor\x12D\n" +
	"\x06region\x18\x03 \x01(\v2,.axnoded.internal.apipb.v1.ComputerUseRegionR\x06region\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x12\x18\n" +
	"\aquality\x18\x05 \x01(\x05R\aquality\x12\x14\n" +
	"\x05scale\x18\x06 \x01(\x01R\x05scale\"V\n" +
	"\x1dComputerUseScreenshotResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\"+\n" +
	"\x19ComputerUseDisplayRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"~\n" +
	"\x1aComputerUseDisplayResponse\x12\x18\n" +
	"\adisplay\x18\x01 \x01(\tR\adisplay\x12\x18\n" +
	"\abackend\x18\x02 \x01(\tR\abackend\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\"\xd1\x01\n" +
	"\x17ComputerUseMouseRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\x11\n" +
	"\x04to_x\x18\x05 \x01(\x05R\x03toX\x12\x11\n" +
	"\x04to_y\x18\x06 \x01(\x05R\x03toY\x12\x16\n" +
	"\x06button\x18\a \x01(\tR\x06button\x12\x1c\n" +
	"\tdirection\x18\b \x01(\tR\tdirection\x12\x16\n" +
	"\x06amount\x18\t \x01(\x05R\x06amount\"\x1a\n" +
	"\x18ComputerUseMouseResponse\"\x81\x01\n" +
	"\x1aComputerUseKeyboardRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x12\n" +
	"\x04keys\x18\x04 \x03(\tR\x04keys\x12\x19\n" +
	"\bdelay_ms\x18\x05 \x01(\x05R\adelayMs\"\x1d\n" +
	"\x1bComputerUseKeyboardResponseBAZ?github.com/cofy-x/axern/runtime/axnoded/internal/apipb/v1;apipbb\x06proto3"

var (
	file_internal_apipb_v1_computer_use_proto_rawDescOnce sync.Once
	file_internal_apipb_v1_computer_use_proto_rawDescData []byte
)

func file_internal_apipb_v1_computer_use_proto_rawDescGZIP() []byte {
	file_internal_apipb_v1_computer_use_proto_rawDescOnce.Do(func() {
		file_internal_apipb_v1_computer_use_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_apipb_v1_computer_use_proto_rawDesc), len(file_internal_apipb_v1_computer_use_proto_rawDesc)))
	})
	return file_internal_apipb_v1_computer_use_proto_rawDescData
}

var file_internal_apipb_v1_computer_use_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_apipb_v1_computer_use_proto_goTypes = []any{
	(*ComputerUseStatusRequest)(nil),      // 0: axnoded.internal.apipb.v1.ComputerUseStatusRequest
	(*ComputerUseStatusResponse)(nil),     // 1: axnoded.internal.apipb.v1.ComputerUseStatusResponse
	(*ComputerUseDependencyStatus)(nil),   // 2: axnoded.internal.apipb.v1.ComputerUseDependencyStatus
	(*ComputerUseRegion)(nil),             // 3: axnoded.internal.apipb.v1.ComputerUseRegion
	(*ComputerUseScreenshotRequest)(nil),  // 4: axnoded.internal.apipb.v1.ComputerUseScreenshotRequest
	(*ComputerUseScreenshotResponse)(nil), // 5: axnoded.internal.apipb.v1.ComputerUseScreenshotResponse
	(*ComputerUseDisplayRequest)(nil),     // 6: axnoded.internal.apipb.v1.ComputerUseDisplayRequest
	(*ComputerUseDisplayResponse)(nil),    // 7: axnoded.internal.apipb.v1.ComputerUseDisplayResponse
	(*ComputerUseMouseRequest)(nil),       // 8: axnoded.internal.apipb.v1.ComputerUseMouseRequest
	(*ComputerUseMouseResponse)(nil),      // 9: axnoded.internal.apipb.v1.ComputerUseMouseResponse
	(*ComputerUseKeyboardRequest)(nil),    // 10: axnoded.internal.apipb.v1.ComputerUseKeyboardRequest
	(*ComputerUseKeyboardResponse)(nil),   // 11: axnoded.internal.apipb.v1.ComputerUseKeyboardResponse
}
var file_internal_apipb_v1_computer_use_proto_depIdxs = []int32{
	2, // 0: axnoded.internal.apipb.v1.ComputerUseStatusResponse.dependencies:type_name -> axnoded.internal.apipb.v1.ComputerUseDependencyStatus
	3, // 1: axnoded.internal.apipb.v1.ComputerUseScreenshotRequest.region:type_name -> axnoded.internal.apipb.v1.ComputerUseRegion
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_apipb_v1_computer_use_proto_init() }
func file_internal_apipb_v1_computer_use_proto_init() {
	if File_internal_apipb_v1_computer_use_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_apipb_v1_computer_use_proto_rawDesc), len(file_internal_apipb_v1_computer_use_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_apipb_v1_computer_use_proto_goTypes,
		DependencyIndexes: file_internal_apipb_v1_computer_use_proto_depIdxs,
		MessageInfos:      file_internal_apipb_v1_computer_use_proto_msgTypes,
	}.Build()
	File_internal_apipb_v1_computer_use_proto = out.File
	file_internal_apipb_v1_computer_use_proto_goTypes = nil
	file_internal_apipb_v1_computer_use_proto_depIdxs = nil
}
