// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: internal/apipb/v1/file.proto

package apipb

import (
	v1 "github.com/cofy-x/axern/sdk/go/gen/axern/common/file/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatFileRequest) Reset() {
	*x = StatFileRequest{}
	mi := &file_internal_apipb_v1_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatFileRequest) ProtoMessage() {}

func (x *StatFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatFileRequest.ProtoReflect.Descriptor instead.
func (*StatFileRequest) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_file_proto_rawDescGZIP(), []int{0}
}

func (x *StatFileRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *StatFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StatFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *v1.SandboxFileInfo    `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatFileResponse) Reset() {
	*x = StatFileResponse{}
	mi := &file_internal_apipb_v1_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatFileResponse) ProtoMessage() {}

func (x *StatFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatFileResponse.ProtoReflect.Descriptor instead.
func (*StatFileResponse) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_file_proto_rawDescGZIP(), []int{1}
}

func (x *StatFileResponse) GetInfo() *v1.SandboxFileInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type ListDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirRequest) Reset() {
	*x = ListDirRequest{}
	mi := &file_internal_apipb_v1_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirRequest) ProtoMessage() {}

func (x *ListDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirRequest.ProtoReflect.Descriptor instead.
func (*ListDirRequest) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_file_proto_rawDescGZIP(), []int{2}
}

func (x *ListDirRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ListDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*v1.SandboxFileInfo  `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirResponse) Reset() {
	*x = ListDirResponse{}
	mi := &file_internal_apipb_v1_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirResponse) ProtoMessage() {}

func (x *ListDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirResponse.ProtoReflect.Descriptor instead.
func (*ListDirResponse) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_file_proto_rawDescGZIP(), []int{3}
}

func (x *ListDirResponse) GetEntries() []*v1.SandboxFileInfo {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_internal_apipb_v1_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_file_proto_rawDescGZIP(), []int{4}
}

func (x *ReadFileRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_internal_apipb_v1_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_file_proto_rawDescGZIP(), []int{5}
}

func (x *ReadFileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	CreateParents bool                   `protobuf:"varint,4,opt,name=create_parents,json=createParents,proto3" json:"create_parents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_internal_apipb_v1_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_file_proto_rawDescGZIP(), []int{6}
}

func (x *WriteFileRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WriteFileRequest) GetCreateParents() bool {
	if x != nil {
		return x.CreateParents
	}
	return false
}

type WriteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResponse) Reset() {
	*x = WriteFileResponse{}
	mi := &file_internal_apipb_v1_file_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResponse) ProtoMessage() {}

func (x *WriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_file_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResponse.ProtoReflect.Descriptor instead.
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_file_proto_rawDescGZIP(), []int{7}
}

type MkdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Parents       bool                   `protobuf:"varint,3,opt,name=parents,proto3" json:"parents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirRequest) Reset() {
	*x = MkdirRequest{}
	mi := &file_internal_apipb_v1_file_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirRequest) ProtoMessage() {}

func (x *MkdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_file_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirRequest.ProtoReflect.Descriptor instead.
func (*MkdirRequest) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_file_proto_rawDescGZIP(), []int{8}
}

func (x *MkdirRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *MkdirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MkdirRequest) GetParents() bool {
	if x != nil {
		return x.Parents
	}
	return false
}

type MkdirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirResponse) Reset() {
	*x = MkdirResponse{}
	mi := &file_internal_apipb_v1_file_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirResponse) ProtoMessage() {}

func (x *MkdirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_file_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirResponse.ProtoReflect.Descriptor instead.
func (*MkdirResponse) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_file_proto_rawDescGZIP(), []int{9}
}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Recursive     bool                   `protobuf:"varint,3,opt,name=recursive,proto3" json:"recursive,omitempty"`
	Force         bool                   `protobuf:"varint,4,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_internal_apipb_v1_file_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_file_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_file_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *RemoveRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RemoveRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

func (x *RemoveRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type RemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveResponse) Reset() {
	*x = RemoveResponse{}
	mi := &file_internal_apipb_v1_file_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResponse) ProtoMessage() {}

func (x *RemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_file_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResponse.ProtoReflect.Descriptor instead.
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_file_proto_rawDescGZIP(), []int{11}
}

type ExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsRequest) Reset() {
	*x = ExistsRequest{}
	mi := &file_internal_apipb_v1_file_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsRequest) ProtoMessage() {}

func (x *ExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_file_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsRequest.ProtoReflect.Descriptor instead.
func (*ExistsRequest) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_file_proto_rawDescGZIP(), []int{12}
}

func (x *ExistsRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ExistsRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsResponse) Reset() {
	*x = ExistsResponse{}
	mi := &file_internal_apipb_v1_file_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsResponse) ProtoMessage() {}

func (x *ExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_file_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsResponse.ProtoReflect.Descriptor instead.
func (*ExistsResponse) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_file_proto_rawDescGZIP(), []int{13}
}

func (x *ExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type CopyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	SrcPath       string                 `protobuf:"bytes,2,opt,name=src_path,json=srcPath,proto3" json:"src_path,omitempty"`
	DstPath       string                 `protobuf:"bytes,3,opt,name=dst_path,json=dstPath,proto3" json:"dst_path,omitempty"`
	Recursive     bool                   `protobuf:"varint,4,opt,name=recursive,proto3" json:"recursive,omitempty"`
	Overwrite     bool                   `protobuf:"varint,5,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyRequest) Reset() {
	*x = CopyRequest{}
	mi := &file_internal_apipb_v1_file_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyRequest) ProtoMessage() {}

func (x *CopyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_file_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyRequest.ProtoReflect.Descriptor instead.
func (*CopyRequest) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_file_proto_rawDescGZIP(), []int{14}
}

func (x *CopyRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *CopyRequest) GetSrcPath() string {
	if x != nil {
		return x.SrcPath
	}
	return ""
}

func (x *CopyRequest) GetDstPath() string {
	if x != nil {
		return x.DstPath
	}
	return ""
}

func (x *CopyRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

func (x *CopyRequest) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

type CopyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyResponse) Reset() {
	*x = CopyResponse{}
	mi := &file_internal_apipb_v1_file_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyResponse) ProtoMessage() {}

func (x *CopyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_file_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyResponse.ProtoReflect.Descriptor instead.
func (*CopyResponse) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_file_proto_rawDescGZIP(), []int{15}
}

type MoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	SrcPath       string                 `protobuf:"bytes,2,opt,name=src_path,json=srcPath,proto3" json:"src_path,omitempty"`
	DstPath       string                 `protobuf:"bytes,3,opt,name=dst_path,json=dstPath,proto3" json:"dst_path,omitempty"`
	Overwrite     bool                   `protobuf:"varint,4,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	mi := &file_internal_apipb_v1_file_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_file_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_file_proto_rawDescGZIP(), []int{16}
}

func (x *MoveRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *MoveRequest) GetSrcPath() string {
	if x != nil {
		return x.SrcPath
	}
	return ""
}

func (x *MoveRequest) GetDstPath() string {
	if x != nil {
		return x.DstPath
	}
	return ""
}

func (x *MoveRequest) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

type MoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveResponse) Reset() {
	*x = MoveResponse{}
	mi := &file_internal_apipb_v1_file_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResponse) ProtoMessage() {}

func (x *MoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_file_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResponse.ProtoReflect.Descriptor instead.
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_file_proto_rawDescGZIP(), []int{17}
}

type ChmodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Mode          uint32                 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Recursive     bool                   `protobuf:"varint,4,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChmodRequest) Reset() {
	*x = ChmodRequest{}
	mi := &file_internal_apipb_v1_file_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChmodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChmodRequest) ProtoMessage() {}

func (x *ChmodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_file_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChmodRequest.ProtoReflect.Descriptor instead.
func (*ChmodRequest) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_file_proto_rawDescGZIP(), []int{18}
}

func (x *ChmodRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ChmodRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ChmodRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *ChmodRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type ChmodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChmodResponse) Reset() {
	*x = ChmodResponse{}
	mi := &file_internal_apipb_v1_file_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChmodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChmodResponse) ProtoMessage() {}

func (x *ChmodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_file_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChmodResponse.ProtoReflect.Descriptor instead.
func (*ChmodResponse) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_file_proto_rawDescGZIP(), []int{19}
}

type TouchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Create        bool                   `protobuf:"varint,3,opt,name=create,proto3" json:"create,omitempty"`
	MtimeNs       int64                  `protobuf:"varint,4,opt,name=mtime_ns,json=mtimeNs,proto3" json:"mtime_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TouchRequest) Reset() {
	*x = TouchRequest{}
	mi := &file_internal_apipb_v1_file_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TouchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TouchRequest) ProtoMessage() {}

func (x *TouchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_file_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TouchRequest.ProtoReflect.Descriptor instead.
func (*TouchRequest) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_file_proto_rawDescGZIP(), []int{20}
}

func (x *TouchRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *TouchRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TouchRequest) GetCreate() bool {
	if x != nil {
		return x.Create
	}
	return false
}

func (x *TouchRequest) GetMtimeNs() int64 {
	if x != nil {
		return x.MtimeNs
	}
	return 0
}

type TouchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TouchResponse) Reset() {
	*x = TouchResponse{}
	mi := &file_internal_apipb_v1_file_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TouchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TouchResponse) ProtoMessage() {}

func (x *TouchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_file_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TouchResponse.ProtoReflect.Descriptor instead.
func (*TouchResponse) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_file_proto_rawDescGZIP(), []int{21}
}

type UploadArchiveRequest struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	ID            string                         `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Path          string                         `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Format        v1.SandboxArchiveFormat        `protobuf:"varint,3,opt,name=format,proto3,enum=axern.common.file.v1.SandboxArchiveFormat" json:"format,omitempty"`
	CreateParents bool                           `protobuf:"varint,4,opt,name=create_parents,json=createParents,proto3" json:"create_parents,omitempty"`
	Overwrite     bool                           `protobuf:"varint,5,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	SymlinkPolicy v1.SandboxArchiveSymlinkPolicy `protobuf:"varint,6,opt,name=symlink_policy,json=symlinkPolicy,proto3,enum=axern.common.file.v1.SandboxArchiveSymlinkPolicy" json:"symlink_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadArchiveRequest) Reset() {
	*x = UploadArchiveRequest{}
	mi := &file_internal_apipb_v1_file_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadArchiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadArchiveRequest) ProtoMessage() {}

func (x *UploadArchiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_file_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadArchiveRequest.ProtoReflect.Descriptor instead.
func (*UploadArchiveRequest) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_file_proto_rawDescGZIP(), []int{22}
}

func (x *UploadArchiveRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *UploadArchiveRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UploadArchiveRequest) GetFormat() v1.SandboxArchiveFormat {
	if x != nil {
		return x.Format
	}
	return v1.SandboxArchiveFormat(0)
}

func (x *UploadArchiveRequest) GetCreateParents() bool {
	if x != nil {
		return x.CreateParents
	}
	return false
}

func (x *UploadArchiveRequest) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

func (x *UploadArchiveRequest) GetSymlinkPolicy() v1.SandboxArchiveSymlinkPolicy {
	if x != nil {
		return x.SymlinkPolicy
	}
	return v1.SandboxArchiveSymlinkPolicy(0)
}

type UploadArchiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadArchiveResponse) Reset() {
	*x = UploadArchiveResponse{}
	mi := &file_internal_apipb_v1_file_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadArchiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadArchiveResponse) ProtoMessage() {}

func (x *UploadArchiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_file_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadArchiveResponse.ProtoReflect.Descriptor instead.
func (*UploadArchiveResponse) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_file_proto_rawDescGZIP(), []int{23}
}

type DownloadArchiveRequest struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	ID            string                         `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Path          string                         `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Format        v1.SandboxArchiveFormat        `protobuf:"varint,3,opt,name=format,proto3,enum=axern.common.file.v1.SandboxArchiveFormat" json:"format,omitempty"`
	SymlinkPolicy v1.SandboxArchiveSymlinkPolicy `protobuf:"varint,4,opt,name=symlink_policy,json=symlinkPolicy,proto3,enum=axern.common.file.v1.SandboxArchiveSymlinkPolicy" json:"symlink_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadArchiveRequest) Reset() {
	*x = DownloadArchiveRequest{}
	mi := &file_internal_apipb_v1_file_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadArchiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadArchiveRequest) ProtoMessage() {}

func (x *DownloadArchiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_file_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadArchiveRequest.ProtoReflect.Descriptor instead.
func (*DownloadArchiveRequest) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_file_proto_rawDescGZIP(), []int{24}
}

func (x *DownloadArchiveRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *DownloadArchiveRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DownloadArchiveRequest) GetFormat() v1.SandboxArchiveFormat {
	if x != nil {
		return x.Format
	}
	return v1.SandboxArchiveFormat(0)
}

func (x *DownloadArchiveRequest) GetSymlinkPolicy() v1.SandboxArchiveSymlinkPolicy {
	if x != nil {
		return x.SymlinkPolicy
	}
	return v1.SandboxArchiveSymlinkPolicy(0)
}

type DownloadArchiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadArchiveResponse) Reset() {
	*x = DownloadArchiveResponse{}
	mi := &file_internal_apipb_v1_file_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadArchiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadArchiveResponse) ProtoMessage() {}

func (x *DownloadArchiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_file_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadArchiveResponse.ProtoReflect.Descriptor instead.
func (*DownloadArchiveResponse) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_file_proto_rawDescGZIP(), []int{25}
}

var File_internal_apipb_v1_file_proto protoreflect.FileDescriptor

const file_internal_apipb_v1_file_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/apipb/v1/file.proto\x12\x19axnoded.internal.apipb.v1\x1a\x1faxern/common/file/v1/file.proto\"5\n" +
	"\x0fStatFileRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"M\n" +
	"\x10StatFileResponse\x129\n" +
	"\x04info\x18\x01 \x01(\v2%.axern.common.file.v1.SandboxFileInfoR\x04info\"4\n" +
	"\x0eListDirRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"R\n" +
	"\x0fListDirResponse\x12?\n" +
	"\aentries\x18\x01 \x03(\v2%.axern.common.file.v1.SandboxFileInfoR\aentries\"5\n" +
	"\x0fReadFileRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"&\n" +
	"\x10ReadFileResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"q\n" +
	"\x10WriteFileRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12%\n" +
	"\x0ecreate_parents\x18\x04 \x01(\bR\rcreateParents\"\x13\n" +
	"\x11WriteFileResponse\"L\n" +
	"\fMkdirRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\aparents\x18\x03 \x01(\bR\aparents\"\x0f\n" +
	"\rMkdirResponse\"g\n" +
	"\rRemoveRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x03 \x01(\bR\trecursive\x12\x14\n" +
	"\x05force\x18\x04 \x01(\bR\x05force\"\x10\n" +
	"\x0eRemoveResponse\"3\n" +
	"\rExistsRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"(\n" +
	"\x0eExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"\x8f\x01\n" +
	"\vCopyRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x19\n" +
	"\bsrc_path\x18\x02 \x01(\tR\asrcPath\x12\x19\n" +
	"\bdst_path\x18\x03 \x01(\tR\adstPath\x12\x1c\n" +
	"\trecursive\x18\x04 \x01(\bR\trecursive\x12\x1c\n" +
	"\toverwrite\x18\x05 \x01(\bR\toverwrite\"\x0e\n" +
	"\fCopyResponse\"q\n" +
	"\vMoveRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x19\n" +
	"\bsrc_path\x18\x02 \x01(\tR\asrcPath\x12\x19\n" +
	"\bdst_path\x18\x03 \x01(\tR\adstPath\x12\x1c\n" +
	"\toverwrite\x18\x04 \x01(\bR\toverwrite\"\x0e\n" +
	"\fMoveResponse\"d\n" +
	"\fChmodRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\x12\x1c\n" +
	"\trecursive\x18\x04 \x01(\bR\trecursive\"\x0f\n" +
	"\rChmodResponse\"e\n" +
	"\fTouchRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06create\x18\x03 \x01(\bR\x06create\x12\x19\n" +
	"\bmtime_ns\x18\x04 \x01(\x03R\amtimeNs\"\x0f\n" +
	"\rTouchResponse\"\x9d\x02\n" +
	"\x14UploadArchiveRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12B\n" +
	"\x06format\x18\x03 \x01(\x0e2*.axern.common.file.v1.SandboxArchiveFormatR\x06format\x12%\n" +
	"\x0ecreate_parents\x18\x04 \x01(\bR\rcreateParents\x12\x1c\n" +
	"\toverwrite\x18\x05 \x01(\bR\toverwrite\x12X\n" +
	"\x0esymlink_policy\x18\x06 \x01(\x0e21.axern.common.file.v1.SandboxArchiveSymlinkPolicyR\rsymlinkPolicy\"\x17\n" +
	"\x15UploadArchiveResponse\"\xda\x01\n" +
	"\x16DownloadArchiveRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12B\n" +
	"\x06format\x18\x03 \x01(\x0e2*.axern.common.file.v1.SandboxArchiveFormatR\x06format\x12X\n" +
	"\x0esymlink_policy\x18\x04 \x01(\x0e21.axern.common.file.v1.SandboxArchiveSymlinkPolicyR\rsymlinkPolicy\"\x19\n" +
	"\x17DownloadArchiveResponseBAZ?github.com/cofy-x/axern/runtime/axnoded/internal/apipb/v1;apipbb\x06proto3"

var (
	file_internal_apipb_v1_file_proto_rawDescOnce sync.Once
	file_internal_apipb_v1_file_proto_rawDescData []byte
)

func file_internal_apipb_v1_file_proto_rawDescGZIP() []byte {
	file_internal_apipb_v1_file_proto_rawDescOnce.Do(func() {
		file_internal_apipb_v1_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_apipb_v1_file_proto_rawDesc), len(file_internal_apipb_v1_file_proto_rawDesc)))
	})
	return file_internal_apipb_v1_file_proto_rawDescData
}

var file_internal_apipb_v1_file_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_internal_apipb_v1_file_proto_goTypes = []any{
	(*StatFileRequest)(nil),             // 0: axnoded.internal.apipb.v1.StatFileRequest
	(*StatFileResponse)(nil),            // 1: axnoded.internal.apipb.v1.StatFileResponse
	(*ListDirRequest)(nil),              // 2: axnoded.internal.apipb.v1.ListDirRequest
	(*ListDirResponse)(nil),             // 3: axnoded.internal.apipb.v1.ListDirResponse
	(*ReadFileRequest)(nil),             // 4: axnoded.internal.apipb.v1.ReadFileRequest
	(*ReadFileResponse)(nil),            // 5: axnoded.internal.apipb.v1.ReadFileResponse
	(*WriteFileRequest)(nil),            // 6: axnoded.internal.apipb.v1.WriteFileRequest
	(*WriteFileResponse)(nil),           // 7: axnoded.internal.apipb.v1.WriteFileResponse
	(*MkdirRequest)(nil),                // 8: axnoded.internal.apipb.v1.MkdirRequest
	(*MkdirResponse)(nil),               // 9: axnoded.internal.apipb.v1.MkdirResponse
	(*RemoveRequest)(nil),               // 10: axnoded.internal.apipb.v1.RemoveRequest
	(*RemoveResponse)(nil),              // 11: axnoded.internal.apipb.v1.RemoveResponse
	(*ExistsRequest)(nil),               // 12: axnoded.internal.apipb.v1.ExistsRequest
	(*ExistsResponse)(nil),              // 13: axnoded.internal.apipb.v1.ExistsResponse
	(*CopyRequest)(nil),                 // 14: axnoded.internal.apipb.v1.CopyRequest
	(*CopyResponse)(nil),                // 15: axnoded.internal.apipb.v1.CopyResponse
	(*MoveRequest)(nil),                 // 16: axnoded.internal.apipb.v1.MoveRequest
	(*MoveResponse)(nil),                // 17: axnoded.internal.apipb.v1.MoveResponse
	(*ChmodRequest)(nil),                // 18: axnoded.internal.apipb.v1.ChmodRequest
	(*ChmodResponse)(nil),               // 19: axnoded.internal.apipb.v1.ChmodResponse
	(*TouchRequest)(nil),                // 20: axnoded.internal.apipb.v1.TouchRequest
	(*TouchResponse)(nil),               // 21: axnoded.internal.apipb.v1.TouchResponse
	(*UploadArchiveRequest)(nil),        // 22: axnoded.internal.apipb.v1.UploadArchiveRequest
	(*UploadArchiveResponse)(nil),       // 23: axnoded.internal.apipb.v1.UploadArchiveResponse
	(*DownloadArchiveRequest)(nil),      // 24: axnoded.internal.apipb.v1.DownloadArchiveRequest
	(*DownloadArchiveResponse)(nil),     // 25: axnoded.internal.apipb.v1.DownloadArchiveResponse
	(*v1.SandboxFileInfo)(nil),          // 26: axern.common.file.v1.SandboxFileInfo
	(v1.SandboxArchiveFormat)(0),        // 27: axern.common.file.v1.SandboxArchiveFormat
	(v1.SandboxArchiveSymlinkPolicy)(0), // 28: axern.common.file.v1.SandboxArchiveSymlinkPolicy
}
var file_internal_apipb_v1_file_proto_depIdxs = []int32{
	26, // 0: axnoded.internal.apipb.v1.StatFileResponse.info:type_name -> axern.common.file.v1.SandboxFileInfo
	26, // 1: axnoded.internal.apipb.v1.ListDirResponse.entries:type_name -> axern.common.file.v1.SandboxFileInfo
	27, // 2: axnoded.internal.apipb.v1.UploadArchiveRequest.format:type_name -> axern.common.file.v1.SandboxArchiveFormat
	28, // 3: axnoded.internal.apipb.v1.UploadArchiveRequest.symlink_policy:type_name -> axern.common.file.v1.SandboxArchiveSymlinkPolicy
	27, // 4: axnoded.internal.apipb.v1.DownloadArchiveRequest.format:type_name -> axern.common.file.v1.SandboxArchiveFormat
	28, // 5: axnoded.internal.apipb.v1.DownloadArchiveRequest.symlink_policy:type_name -> axern.common.file.v1.SandboxArchiveSymlinkPolicy
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_internal_apipb_v1_file_proto_init() }
func file_internal_apipb_v1_file_proto_init() {
	if File_internal_apipb_v1_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_apipb_v1_file_proto_rawDesc), len(file_internal_apipb_v1_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_apipb_v1_file_proto_goTypes,
		DependencyIndexes: file_internal_apipb_v1_file_proto_depIdxs,
		MessageInfos:      file_internal_apipb_v1_file_proto_msgTypes,
	}.Build()
	File_internal_apipb_v1_file_proto = out.File
	file_internal_apipb_v1_file_proto_goTypes = nil
	file_internal_apipb_v1_file_proto_depIdxs = nil
}
