// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: internal/apipb/v1/process.proto

package apipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Command       []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	Timeout       int64                  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Cwd           string                 `protobuf:"bytes,5,opt,name=cwd,proto3" json:"cwd,omitempty"`
	User          string                 `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	ManagedProxy  *ManagedProxySpec      `protobuf:"bytes,7,opt,name=managed_proxy,json=managedProxy,proto3" json:"managed_proxy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_internal_apipb_v1_process_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_process_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_process_proto_rawDescGZIP(), []int{0}
}

func (x *ExecRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ExecRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ExecRequest) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *ExecRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ExecRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ExecRequest) GetManagedProxy() *ManagedProxySpec {
	if x != nil {
		return x.ManagedProxy
	}
	return nil
}

type ManagedProxySpec struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Provider            string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	UpstreamBaseUrl     string                 `protobuf:"bytes,2,opt,name=upstream_base_url,json=upstreamBaseUrl,proto3" json:"upstream_base_url,omitempty"`
	UpstreamBearerToken string                 `protobuf:"bytes,3,opt,name=upstream_bearer_token,json=upstreamBearerToken,proto3" json:"upstream_bearer_token,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ManagedProxySpec) Reset() {
	*x = ManagedProxySpec{}
	mi := &file_internal_apipb_v1_process_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedProxySpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedProxySpec) ProtoMessage() {}

func (x *ManagedProxySpec) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_process_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedProxySpec.ProtoReflect.Descriptor instead.
func (*ManagedProxySpec) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_process_proto_rawDescGZIP(), []int{1}
}

func (x *ManagedProxySpec) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ManagedProxySpec) GetUpstreamBaseUrl() string {
	if x != nil {
		return x.UpstreamBaseUrl
	}
	return ""
}

func (x *ManagedProxySpec) GetUpstreamBearerToken() string {
	if x != nil {
		return x.UpstreamBearerToken
	}
	return ""
}

type ManagedProxyReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	RequestCount  int32                  `protobuf:"varint,2,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`
	ResponseCount int32                  `protobuf:"varint,3,opt,name=response_count,json=responseCount,proto3" json:"response_count,omitempty"`
	ErrorCount    int32                  `protobuf:"varint,4,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	ReportJson    []byte                 `protobuf:"bytes,5,opt,name=report_json,json=reportJson,proto3" json:"report_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagedProxyReport) Reset() {
	*x = ManagedProxyReport{}
	mi := &file_internal_apipb_v1_process_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedProxyReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedProxyReport) ProtoMessage() {}

func (x *ManagedProxyReport) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_process_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedProxyReport.ProtoReflect.Descriptor instead.
func (*ManagedProxyReport) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_process_proto_rawDescGZIP(), []int{2}
}

func (x *ManagedProxyReport) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ManagedProxyReport) GetRequestCount() int32 {
	if x != nil {
		return x.RequestCount
	}
	return 0
}

func (x *ManagedProxyReport) GetResponseCount() int32 {
	if x != nil {
		return x.ResponseCount
	}
	return 0
}

func (x *ManagedProxyReport) GetErrorCount() int32 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

func (x *ManagedProxyReport) GetReportJson() []byte {
	if x != nil {
		return x.ReportJson
	}
	return nil
}

type ExecResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ExitCode           int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout             []byte                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr             []byte                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	StdoutTruncated    bool                   `protobuf:"varint,4,opt,name=stdout_truncated,json=stdoutTruncated,proto3" json:"stdout_truncated,omitempty"`
	StderrTruncated    bool                   `protobuf:"varint,5,opt,name=stderr_truncated,json=stderrTruncated,proto3" json:"stderr_truncated,omitempty"`
	ManagedProxyReport *ManagedProxyReport    `protobuf:"bytes,6,opt,name=managed_proxy_report,json=managedProxyReport,proto3" json:"managed_proxy_report,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_internal_apipb_v1_process_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_process_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_process_proto_rawDescGZIP(), []int{3}
}

func (x *ExecResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *ExecResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *ExecResponse) GetStdoutTruncated() bool {
	if x != nil {
		return x.StdoutTruncated
	}
	return false
}

func (x *ExecResponse) GetStderrTruncated() bool {
	if x != nil {
		return x.StderrTruncated
	}
	return false
}

func (x *ExecResponse) GetManagedProxyReport() *ManagedProxyReport {
	if x != nil {
		return x.ManagedProxyReport
	}
	return nil
}

type ExecStreamOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Command       []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	Tty           bool                   `protobuf:"varint,3,opt,name=tty,proto3" json:"tty,omitempty"`
	Timeout       int64                  `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Env           map[string]string      `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Cwd           string                 `protobuf:"bytes,6,opt,name=cwd,proto3" json:"cwd,omitempty"`
	User          string                 `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
	InitialSize   *TerminalResize        `protobuf:"bytes,8,opt,name=initial_size,json=initialSize,proto3" json:"initial_size,omitempty"`
	ManagedProxy  *ManagedProxySpec      `protobuf:"bytes,9,opt,name=managed_proxy,json=managedProxy,proto3" json:"managed_proxy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecStreamOpen) Reset() {
	*x = ExecStreamOpen{}
	mi := &file_internal_apipb_v1_process_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecStreamOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStreamOpen) ProtoMessage() {}

func (x *ExecStreamOpen) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_process_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStreamOpen.ProtoReflect.Descriptor instead.
func (*ExecStreamOpen) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_process_proto_rawDescGZIP(), []int{4}
}

func (x *ExecStreamOpen) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ExecStreamOpen) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ExecStreamOpen) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

func (x *ExecStreamOpen) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *ExecStreamOpen) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecStreamOpen) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ExecStreamOpen) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ExecStreamOpen) GetInitialSize() *TerminalResize {
	if x != nil {
		return x.InitialSize
	}
	return nil
}

func (x *ExecStreamOpen) GetManagedProxy() *ManagedProxySpec {
	if x != nil {
		return x.ManagedProxy
	}
	return nil
}

type ExecStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecStreamRequest_Open
	//	*ExecStreamRequest_Stdin
	//	*ExecStreamRequest_Resize
	//	*ExecStreamRequest_CloseStdin
	Payload       isExecStreamRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecStreamRequest) Reset() {
	*x = ExecStreamRequest{}
	mi := &file_internal_apipb_v1_process_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStreamRequest) ProtoMessage() {}

func (x *ExecStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_process_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStreamRequest.ProtoReflect.Descriptor instead.
func (*ExecStreamRequest) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_process_proto_rawDescGZIP(), []int{5}
}

func (x *ExecStreamRequest) GetPayload() isExecStreamRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecStreamRequest) GetOpen() *ExecStreamOpen {
	if x != nil {
		if x, ok := x.Payload.(*ExecStreamRequest_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *ExecStreamRequest) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ExecStreamRequest_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *ExecStreamRequest) GetResize() *TerminalResize {
	if x != nil {
		if x, ok := x.Payload.(*ExecStreamRequest_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *ExecStreamRequest) GetCloseStdin() bool {
	if x != nil {
		if x, ok := x.Payload.(*ExecStreamRequest_CloseStdin); ok {
			return x.CloseStdin
		}
	}
	return false
}

type isExecStreamRequest_Payload interface {
	isExecStreamRequest_Payload()
}

type ExecStreamRequest_Open struct {
	Open *ExecStreamOpen `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type ExecStreamRequest_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type ExecStreamRequest_Resize struct {
	Resize *TerminalResize `protobuf:"bytes,3,opt,name=resize,proto3,oneof"`
}

type ExecStreamRequest_CloseStdin struct {
	CloseStdin bool `protobuf:"varint,4,opt,name=close_stdin,json=closeStdin,proto3,oneof"`
}

func (*ExecStreamRequest_Open) isExecStreamRequest_Payload() {}

func (*ExecStreamRequest_Stdin) isExecStreamRequest_Payload() {}

func (*ExecStreamRequest_Resize) isExecStreamRequest_Payload() {}

func (*ExecStreamRequest_CloseStdin) isExecStreamRequest_Payload() {}

type ExecExit struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ExitCode           int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Message            string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ManagedProxyReport *ManagedProxyReport    `protobuf:"bytes,3,opt,name=managed_proxy_report,json=managedProxyReport,proto3" json:"managed_proxy_report,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExecExit) Reset() {
	*x = ExecExit{}
	mi := &file_internal_apipb_v1_process_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecExit) ProtoMessage() {}

func (x *ExecExit) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_process_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecExit.ProtoReflect.Descriptor instead.
func (*ExecExit) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_process_proto_rawDescGZIP(), []int{6}
}

func (x *ExecExit) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecExit) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecExit) GetManagedProxyReport() *ManagedProxyReport {
	if x != nil {
		return x.ManagedProxyReport
	}
	return nil
}

type ExecStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecStreamResponse_Stdout
	//	*ExecStreamResponse_Stderr
	//	*ExecStreamResponse_Exit
	Payload       isExecStreamResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecStreamResponse) Reset() {
	*x = ExecStreamResponse{}
	mi := &file_internal_apipb_v1_process_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStreamResponse) ProtoMessage() {}

func (x *ExecStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_process_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStreamResponse.ProtoReflect.Descriptor instead.
func (*ExecStreamResponse) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_process_proto_rawDescGZIP(), []int{7}
}

func (x *ExecStreamResponse) GetPayload() isExecStreamResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecStreamResponse) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ExecStreamResponse_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ExecStreamResponse) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ExecStreamResponse_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ExecStreamResponse) GetExit() *ExecExit {
	if x != nil {
		if x, ok := x.Payload.(*ExecStreamResponse_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

type isExecStreamResponse_Payload interface {
	isExecStreamResponse_Payload()
}

type ExecStreamResponse_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ExecStreamResponse_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type ExecStreamResponse_Exit struct {
	Exit *ExecExit `protobuf:"bytes,3,opt,name=exit,proto3,oneof"`
}

func (*ExecStreamResponse_Stdout) isExecStreamResponse_Payload() {}

func (*ExecStreamResponse_Stderr) isExecStreamResponse_Payload() {}

func (*ExecStreamResponse_Exit) isExecStreamResponse_Payload() {}

type ProcessOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Command       []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	Tty           bool                   `protobuf:"varint,3,opt,name=tty,proto3" json:"tty,omitempty"`
	Timeout       int64                  `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Env           map[string]string      `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Cwd           string                 `protobuf:"bytes,6,opt,name=cwd,proto3" json:"cwd,omitempty"`
	User          string                 `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
	ManagedProxy  *ManagedProxySpec      `protobuf:"bytes,8,opt,name=managed_proxy,json=managedProxy,proto3" json:"managed_proxy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessOpen) Reset() {
	*x = ProcessOpen{}
	mi := &file_internal_apipb_v1_process_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessOpen) ProtoMessage() {}

func (x *ProcessOpen) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_process_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessOpen.ProtoReflect.Descriptor instead.
func (*ProcessOpen) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_process_proto_rawDescGZIP(), []int{8}
}

func (x *ProcessOpen) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ProcessOpen) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ProcessOpen) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

func (x *ProcessOpen) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *ProcessOpen) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ProcessOpen) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ProcessOpen) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ProcessOpen) GetManagedProxy() *ManagedProxySpec {
	if x != nil {
		return x.ManagedProxy
	}
	return nil
}

type ProcessSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signal        string                 `protobuf:"bytes,1,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessSignal) Reset() {
	*x = ProcessSignal{}
	mi := &file_internal_apipb_v1_process_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessSignal) ProtoMessage() {}

func (x *ProcessSignal) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_process_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessSignal.ProtoReflect.Descriptor instead.
func (*ProcessSignal) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_process_proto_rawDescGZIP(), []int{9}
}

func (x *ProcessSignal) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

type ProcessReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessReady) Reset() {
	*x = ProcessReady{}
	mi := &file_internal_apipb_v1_process_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessReady) ProtoMessage() {}

func (x *ProcessReady) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_process_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessReady.ProtoReflect.Descriptor instead.
func (*ProcessReady) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_process_proto_rawDescGZIP(), []int{10}
}

type ProcessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ProcessRequest_Open
	//	*ProcessRequest_Stdin
	//	*ProcessRequest_Resize
	//	*ProcessRequest_CloseStdin
	//	*ProcessRequest_Signal
	Payload       isProcessRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRequest) Reset() {
	*x = ProcessRequest{}
	mi := &file_internal_apipb_v1_process_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequest) ProtoMessage() {}

func (x *ProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_process_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRequest.ProtoReflect.Descriptor instead.
func (*ProcessRequest) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_process_proto_rawDescGZIP(), []int{11}
}

func (x *ProcessRequest) GetPayload() isProcessRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProcessRequest) GetOpen() *ProcessOpen {
	if x != nil {
		if x, ok := x.Payload.(*ProcessRequest_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *ProcessRequest) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ProcessRequest_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *ProcessRequest) GetResize() *TerminalResize {
	if x != nil {
		if x, ok := x.Payload.(*ProcessRequest_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *ProcessRequest) GetCloseStdin() bool {
	if x != nil {
		if x, ok := x.Payload.(*ProcessRequest_CloseStdin); ok {
			return x.CloseStdin
		}
	}
	return false
}

func (x *ProcessRequest) GetSignal() *ProcessSignal {
	if x != nil {
		if x, ok := x.Payload.(*ProcessRequest_Signal); ok {
			return x.Signal
		}
	}
	return nil
}

type isProcessRequest_Payload interface {
	isProcessRequest_Payload()
}

type ProcessRequest_Open struct {
	Open *ProcessOpen `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type ProcessRequest_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type ProcessRequest_Resize struct {
	Resize *TerminalResize `protobuf:"bytes,3,opt,name=resize,proto3,oneof"`
}

type ProcessRequest_CloseStdin struct {
	CloseStdin bool `protobuf:"varint,4,opt,name=close_stdin,json=closeStdin,proto3,oneof"`
}

type ProcessRequest_Signal struct {
	Signal *ProcessSignal `protobuf:"bytes,5,opt,name=signal,proto3,oneof"`
}

func (*ProcessRequest_Open) isProcessRequest_Payload() {}

func (*ProcessRequest_Stdin) isProcessRequest_Payload() {}

func (*ProcessRequest_Resize) isProcessRequest_Payload() {}

func (*ProcessRequest_CloseStdin) isProcessRequest_Payload() {}

func (*ProcessRequest_Signal) isProcessRequest_Payload() {}

type ProcessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ProcessResponse_Stdout
	//	*ProcessResponse_Stderr
	//	*ProcessResponse_Exit
	//	*ProcessResponse_Ready
	Payload       isProcessResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessResponse) Reset() {
	*x = ProcessResponse{}
	mi := &file_internal_apipb_v1_process_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessResponse) ProtoMessage() {}

func (x *ProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_process_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessResponse.ProtoReflect.Descriptor instead.
func (*ProcessResponse) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_process_proto_rawDescGZIP(), []int{12}
}

func (x *ProcessResponse) GetPayload() isProcessResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProcessResponse) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ProcessResponse_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ProcessResponse) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ProcessResponse_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ProcessResponse) GetExit() *ExecExit {
	if x != nil {
		if x, ok := x.Payload.(*ProcessResponse_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

func (x *ProcessResponse) GetReady() *ProcessReady {
	if x != nil {
		if x, ok := x.Payload.(*ProcessResponse_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

type isProcessResponse_Payload interface {
	isProcessResponse_Payload()
}

type ProcessResponse_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ProcessResponse_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type ProcessResponse_Exit struct {
	Exit *ExecExit `protobuf:"bytes,3,opt,name=exit,proto3,oneof"`
}

type ProcessResponse_Ready struct {
	Ready *ProcessReady `protobuf:"bytes,4,opt,name=ready,proto3,oneof"`
}

func (*ProcessResponse_Stdout) isProcessResponse_Payload() {}

func (*ProcessResponse_Stderr) isProcessResponse_Payload() {}

func (*ProcessResponse_Exit) isProcessResponse_Payload() {}

func (*ProcessResponse_Ready) isProcessResponse_Payload() {}

type ImageProcessMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SandboxPath   string                 `protobuf:"bytes,1,opt,name=sandbox_path,json=sandboxPath,proto3" json:"sandbox_path,omitempty"`
	TargetPath    string                 `protobuf:"bytes,2,opt,name=target_path,json=targetPath,proto3" json:"target_path,omitempty"`
	Readonly      bool                   `protobuf:"varint,3,opt,name=readonly,proto3" json:"readonly,omitempty"`
	Options       []string               `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageProcessMount) Reset() {
	*x = ImageProcessMount{}
	mi := &file_internal_apipb_v1_process_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageProcessMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageProcessMount) ProtoMessage() {}

func (x *ImageProcessMount) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_process_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageProcessMount.ProtoReflect.Descriptor instead.
func (*ImageProcessMount) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_process_proto_rawDescGZIP(), []int{13}
}

func (x *ImageProcessMount) GetSandboxPath() string {
	if x != nil {
		return x.SandboxPath
	}
	return ""
}

func (x *ImageProcessMount) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

func (x *ImageProcessMount) GetReadonly() bool {
	if x != nil {
		return x.Readonly
	}
	return false
}

func (x *ImageProcessMount) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

type ImageProcessSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Command       []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	Tty           bool                   `protobuf:"varint,3,opt,name=tty,proto3" json:"tty,omitempty"`
	Timeout       int64                  `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Env           map[string]string      `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Cwd           string                 `protobuf:"bytes,6,opt,name=cwd,proto3" json:"cwd,omitempty"`
	User          string                 `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
	Mounts        []*ImageProcessMount   `protobuf:"bytes,8,rep,name=mounts,proto3" json:"mounts,omitempty"`
	ManagedProxy  *ManagedProxySpec      `protobuf:"bytes,9,opt,name=managed_proxy,json=managedProxy,proto3" json:"managed_proxy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageProcessSpec) Reset() {
	*x = ImageProcessSpec{}
	mi := &file_internal_apipb_v1_process_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageProcessSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageProcessSpec) ProtoMessage() {}

func (x *ImageProcessSpec) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_process_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageProcessSpec.ProtoReflect.Descriptor instead.
func (*ImageProcessSpec) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_process_proto_rawDescGZIP(), []int{14}
}

func (x *ImageProcessSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ImageProcessSpec) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ImageProcessSpec) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

func (x *ImageProcessSpec) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *ImageProcessSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ImageProcessSpec) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ImageProcessSpec) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ImageProcessSpec) GetMounts() []*ImageProcessMount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *ImageProcessSpec) GetManagedProxy() *ManagedProxySpec {
	if x != nil {
		return x.ManagedProxy
	}
	return nil
}

type ExecImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Spec          *ImageProcessSpec      `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecImageRequest) Reset() {
	*x = ExecImageRequest{}
	mi := &file_internal_apipb_v1_process_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecImageRequest) ProtoMessage() {}

func (x *ExecImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_process_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecImageRequest.ProtoReflect.Descriptor instead.
func (*ExecImageRequest) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_process_proto_rawDescGZIP(), []int{15}
}

func (x *ExecImageRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ExecImageRequest) GetSpec() *ImageProcessSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type ExecImageResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ExitCode           int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout             []byte                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr             []byte                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	StdoutTruncated    bool                   `protobuf:"varint,4,opt,name=stdout_truncated,json=stdoutTruncated,proto3" json:"stdout_truncated,omitempty"`
	StderrTruncated    bool                   `protobuf:"varint,5,opt,name=stderr_truncated,json=stderrTruncated,proto3" json:"stderr_truncated,omitempty"`
	ManagedProxyReport *ManagedProxyReport    `protobuf:"bytes,6,opt,name=managed_proxy_report,json=managedProxyReport,proto3" json:"managed_proxy_report,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExecImageResponse) Reset() {
	*x = ExecImageResponse{}
	mi := &file_internal_apipb_v1_process_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecImageResponse) ProtoMessage() {}

func (x *ExecImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_process_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecImageResponse.ProtoReflect.Descriptor instead.
func (*ExecImageResponse) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_process_proto_rawDescGZIP(), []int{16}
}

func (x *ExecImageResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecImageResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *ExecImageResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *ExecImageResponse) GetStdoutTruncated() bool {
	if x != nil {
		return x.StdoutTruncated
	}
	return false
}

func (x *ExecImageResponse) GetStderrTruncated() bool {
	if x != nil {
		return x.StderrTruncated
	}
	return false
}

func (x *ExecImageResponse) GetManagedProxyReport() *ManagedProxyReport {
	if x != nil {
		return x.ManagedProxyReport
	}
	return nil
}

type ProcessImageOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Spec          *ImageProcessSpec      `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessImageOpen) Reset() {
	*x = ProcessImageOpen{}
	mi := &file_internal_apipb_v1_process_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessImageOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessImageOpen) ProtoMessage() {}

func (x *ProcessImageOpen) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_process_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessImageOpen.ProtoReflect.Descriptor instead.
func (*ProcessImageOpen) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_process_proto_rawDescGZIP(), []int{17}
}

func (x *ProcessImageOpen) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *ProcessImageOpen) GetSpec() *ImageProcessSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type ProcessImageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ProcessImageRequest_Open
	//	*ProcessImageRequest_Stdin
	//	*ProcessImageRequest_Resize
	//	*ProcessImageRequest_CloseStdin
	//	*ProcessImageRequest_Signal
	Payload       isProcessImageRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessImageRequest) Reset() {
	*x = ProcessImageRequest{}
	mi := &file_internal_apipb_v1_process_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessImageRequest) ProtoMessage() {}

func (x *ProcessImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_process_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessImageRequest.ProtoReflect.Descriptor instead.
func (*ProcessImageRequest) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_process_proto_rawDescGZIP(), []int{18}
}

func (x *ProcessImageRequest) GetPayload() isProcessImageRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProcessImageRequest) GetOpen() *ProcessImageOpen {
	if x != nil {
		if x, ok := x.Payload.(*ProcessImageRequest_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *ProcessImageRequest) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ProcessImageRequest_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *ProcessImageRequest) GetResize() *TerminalResize {
	if x != nil {
		if x, ok := x.Payload.(*ProcessImageRequest_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *ProcessImageRequest) GetCloseStdin() bool {
	if x != nil {
		if x, ok := x.Payload.(*ProcessImageRequest_CloseStdin); ok {
			return x.CloseStdin
		}
	}
	return false
}

func (x *ProcessImageRequest) GetSignal() *ProcessSignal {
	if x != nil {
		if x, ok := x.Payload.(*ProcessImageRequest_Signal); ok {
			return x.Signal
		}
	}
	return nil
}

type isProcessImageRequest_Payload interface {
	isProcessImageRequest_Payload()
}

type ProcessImageRequest_Open struct {
	Open *ProcessImageOpen `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type ProcessImageRequest_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type ProcessImageRequest_Resize struct {
	Resize *TerminalResize `protobuf:"bytes,3,opt,name=resize,proto3,oneof"`
}

type ProcessImageRequest_CloseStdin struct {
	CloseStdin bool `protobuf:"varint,4,opt,name=close_stdin,json=closeStdin,proto3,oneof"`
}

type ProcessImageRequest_Signal struct {
	Signal *ProcessSignal `protobuf:"bytes,5,opt,name=signal,proto3,oneof"`
}

func (*ProcessImageRequest_Open) isProcessImageRequest_Payload() {}

func (*ProcessImageRequest_Stdin) isProcessImageRequest_Payload() {}

func (*ProcessImageRequest_Resize) isProcessImageRequest_Payload() {}

func (*ProcessImageRequest_CloseStdin) isProcessImageRequest_Payload() {}

func (*ProcessImageRequest_Signal) isProcessImageRequest_Payload() {}

type ProcessImageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ProcessImageResponse_Stdout
	//	*ProcessImageResponse_Stderr
	//	*ProcessImageResponse_Exit
	//	*ProcessImageResponse_Ready
	Payload       isProcessImageResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessImageResponse) Reset() {
	*x = ProcessImageResponse{}
	mi := &file_internal_apipb_v1_process_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessImageResponse) ProtoMessage() {}

func (x *ProcessImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_apipb_v1_process_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessImageResponse.ProtoReflect.Descriptor instead.
func (*ProcessImageResponse) Descriptor() ([]byte, []int) {
	return file_internal_apipb_v1_process_proto_rawDescGZIP(), []int{19}
}

func (x *ProcessImageResponse) GetPayload() isProcessImageResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProcessImageResponse) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ProcessImageResponse_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ProcessImageResponse) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ProcessImageResponse_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ProcessImageResponse) GetExit() *ExecExit {
	if x != nil {
		if x, ok := x.Payload.(*ProcessImageResponse_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

func (x *ProcessImageResponse) GetReady() *ProcessReady {
	if x != nil {
		if x, ok := x.Payload.(*ProcessImageResponse_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

type isProcessImageResponse_Payload interface {
	isProcessImageResponse_Payload()
}

type ProcessImageResponse_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ProcessImageResponse_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type ProcessImageResponse_Exit struct {
	Exit *ExecExit `protobuf:"bytes,3,opt,name=exit,proto3,oneof"`
}

type ProcessImageResponse_Ready struct {
	Ready *ProcessReady `protobuf:"bytes,4,opt,name=ready,proto3,oneof"`
}

func (*ProcessImageResponse_Stdout) isProcessImageResponse_Payload() {}

func (*ProcessImageResponse_Stderr) isProcessImageResponse_Payload() {}

func (*ProcessImageResponse_Exit) isProcessImageResponse_Payload() {}

func (*ProcessImageResponse_Ready) isProcessImageResponse_Payload() {}

var File_internal_apipb_v1_process_proto protoreflect.FileDescriptor

const file_internal_apipb_v1_process_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/apipb/v1/process.proto\x12\x19axnoded.internal.apipb.v1\x1a(internal/apipb/v1/axnoded_internal.proto\"\xc4\x02\n" +
	"\vExecRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x03R\atimeout\x12A\n" +
	"\x03env\x18\x04 \x03(\v2/.axnoded.internal.apipb.v1.ExecRequest.EnvEntryR\x03env\x12\x10\n" +
	"\x03cwd\x18\x05 \x01(\tR\x03cwd\x12\x12\n" +
	"\x04user\x18\x06 \x01(\tR\x04user\x12P\n" +
	"\rmanaged_proxy\x18\a \x01(\v2+.axnoded.internal.apipb.v1.ManagedProxySpecR\fmanagedProxy\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8e\x01\n" +
	"\x10ManagedProxySpec\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12*\n" +
	"\x11upstream_base_url\x18\x02 \x01(\tR\x0fupstreamBaseUrl\x122\n" +
	"\x15upstream_bearer_token\x18\x03 \x01(\tR\x13upstreamBearerToken\"\xbe\x01\n" +
	"\x12ManagedProxyReport\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12#\n" +
	"\rrequest_count\x18\x02 \x01(\x05R\frequestCount\x12%\n" +
	"\x0eresponse_count\x18\x03 \x01(\x05R\rresponseCount\x12\x1f\n" +
	"\verror_count\x18\x04 \x01(\x05R\n" +
	"errorCount\x12\x1f\n" +
	"\vreport_json\x18\x05 \x01(\fR\n" +
	"reportJson\"\x92\x02\n" +
	"\fExecResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\fR\x06stderr\x12)\n" +
	"\x10stdout_truncated\x18\x04 \x01(\bR\x0fstdoutTruncated\x12)\n" +
	"\x10stderr_truncated\x18\x05 \x01(\bR\x0fstderrTruncated\x12_\n" +
	"\x14managed_proxy_report\x18\x06 \x01(\v2-.axnoded.internal.apipb.v1.ManagedProxyReportR\x12managedProxyReport\"\xaa\x03\n" +
	"\x0eExecStreamOpen\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x10\n" +
	"\x03tty\x18\x03 \x01(\bR\x03tty\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\x03R\atimeout\x12D\n" +
	"\x03env\x18\x05 \x03(\v22.axnoded.internal.apipb.v1.ExecStreamOpen.EnvEntryR\x03env\x12\x10\n" +
	"\x03cwd\x18\x06 \x01(\tR\x03cwd\x12\x12\n" +
	"\x04user\x18\a \x01(\tR\x04user\x12L\n" +
	"\finitial_size\x18\b \x01(\v2).axnoded.internal.apipb.v1.TerminalResizeR\vinitialSize\x12P\n" +
	"\rmanaged_proxy\x18\t \x01(\v2+.axnoded.internal.apipb.v1.ManagedProxySpecR\fmanagedProxy\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdf\x01\n" +
	"\x11ExecStreamRequest\x12?\n" +
	"\x04open\x18\x01 \x01(\v2).axnoded.internal.apipb.v1.ExecStreamOpenH\x00R\x04open\x12\x16\n" +
	"\x05stdin\x18\x02 \x01(\fH\x00R\x05stdin\x12C\n" +
	"\x06resize\x18\x03 \x01(\v2).axnoded.internal.apipb.v1.TerminalResizeH\x00R\x06resize\x12!\n" +
	"\vclose_stdin\x18\x04 \x01(\bH\x00R\n" +
	"closeStdinB\t\n" +
	"\apayload\"\xa2\x01\n" +
	"\bExecExit\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12_\n" +
	"\x14managed_proxy_report\x18\x03 \x01(\v2-.axnoded.internal.apipb.v1.ManagedProxyReportR\x12managedProxyReport\"\x8e\x01\n" +
	"\x12ExecStreamResponse\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x129\n" +
	"\x04exit\x18\x03 \x01(\v2#.axnoded.internal.apipb.v1.ExecExitH\x00R\x04exitB\t\n" +
	"\apayload\"\xd6\x02\n" +
	"\vProcessOpen\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x10\n" +
	"\x03tty\x18\x03 \x01(\bR\x03tty\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\x03R\atimeout\x12A\n" +
	"\x03env\x18\x05 \x03(\v2/.axnoded.internal.apipb.v1.ProcessOpen.EnvEntryR\x03env\x12\x10\n" +
	"\x03cwd\x18\x06 \x01(\tR\x03cwd\x12\x12\n" +
	"\x04user\x18\a \x01(\tR\x04user\x12P\n" +
	"\rmanaged_proxy\x18\b \x01(\v2+.axnoded.internal.apipb.v1.ManagedProxySpecR\fmanagedProxy\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"'\n" +
	"\rProcessSignal\x12\x16\n" +
	"\x06signal\x18\x01 \x01(\tR\x06signal\"\x0e\n" +
	"\fProcessReady\"\x9d\x02\n" +
	"\x0eProcessRequest\x12<\n" +
	"\x04open\x18\x01 \x01(\v2&.axnoded.internal.apipb.v1.ProcessOpenH\x00R\x04open\x12\x16\n" +
	"\x05stdin\x18\x02 \x01(\fH\x00R\x05stdin\x12C\n" +
	"\x06resize\x18\x03 \x01(\v2).axnoded.internal.apipb.v1.TerminalResizeH\x00R\x06resize\x12!\n" +
	"\vclose_stdin\x18\x04 \x01(\bH\x00R\n" +
	"closeStdin\x12B\n" +
	"\x06signal\x18\x05 \x01(\v2(.axnoded.internal.apipb.v1.ProcessSignalH\x00R\x06signalB\t\n" +
	"\apayload\"\xcc\x01\n" +
	"\x0fProcessResponse\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x129\n" +
	"\x04exit\x18\x03 \x01(\v2#.axnoded.internal.apipb.v1.ExecExitH\x00R\x04exit\x12?\n" +
	"\x05ready\x18\x04 \x01(\v2'.axnoded.internal.apipb.v1.ProcessReadyH\x00R\x05readyB\t\n" +
	"\apayload\"\x8d\x01\n" +
	"\x11ImageProcessMount\x12!\n" +
	"\fsandbox_path\x18\x01 \x01(\tR\vsandboxPath\x12\x1f\n" +
	"\vtarget_path\x18\x02 \x01(\tR\n" +
	"targetPath\x12\x1a\n" +
	"\breadonly\x18\x03 \x01(\bR\breadonly\x12\x18\n" +
	"\aoptions\x18\x04 \x03(\tR\aoptions\"\xac\x03\n" +
	"\x10ImageProcessSpec\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x10\n" +
	"\x03tty\x18\x03 \x01(\bR\x03tty\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\x03R\atimeout\x12F\n" +
	"\x03env\x18\x05 \x03(\v24.axnoded.internal.apipb.v1.ImageProcessSpec.EnvEntryR\x03env\x12\x10\n" +
	"\x03cwd\x18\x06 \x01(\tR\x03cwd\x12\x12\n" +
	"\x04user\x18\a \x01(\tR\x04user\x12D\n" +
	"\x06mounts\x18\b \x03(\v2,.axnoded.internal.apipb.v1.ImageProcessMountR\x06mounts\x12P\n" +
	"\rmanaged_proxy\x18\t \x01(\v2+.axnoded.internal.apipb.v1.ManagedProxySpecR\fmanagedProxy\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"c\n" +
	"\x10ExecImageRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12?\n" +
	"\x04spec\x18\x02 \x01(\v2+.axnoded.internal.apipb.v1.ImageProcessSpecR\x04spec\"\x97\x02\n" +
	"\x11ExecImageResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\fR\x06stderr\x12)\n" +
	"\x10stdout_truncated\x18\x04 \x01(\bR\x0fstdoutTruncated\x12)\n" +
	"\x10stderr_truncated\x18\x05 \x01(\bR\x0fstderrTruncated\x12_\n" +
	"\x14managed_proxy_report\x18\x06 \x01(\v2-.axnoded.internal.apipb.v1.ManagedProxyReportR\x12managedProxyReport\"c\n" +
	"\x10ProcessImageOpen\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12?\n" +
	"\x04spec\x18\x02 \x01(\v2+.axnoded.internal.apipb.v1.ImageProcessSpecR\x04spec\"\xa7\x02\n" +
	"\x13ProcessImageRequest\x12A\n" +
	"\x04open\x18\x01 \x01(\v2+.axnoded.internal.apipb.v1.ProcessImageOpenH\x00R\x04open\x12\x16\n" +
	"\x05stdin\x18\x02 \x01(\fH\x00R\x05stdin\x12C\n" +
	"\x06resize\x18\x03 \x01(\v2).axnoded.internal.apipb.v1.TerminalResizeH\x00R\x06resize\x12!\n" +
	"\vclose_stdin\x18\x04 \x01(\bH\x00R\n" +
	"closeStdin\x12B\n" +
	"\x06signal\x18\x05 \x01(\v2(.axnoded.internal.apipb.v1.ProcessSignalH\x00R\x06signalB\t\n" +
	"\apayload\"\xd1\x01\n" +
	"\x14ProcessImageResponse\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x129\n" +
	"\x04exit\x18\x03 \x01(\v2#.axnoded.internal.apipb.v1.ExecExitH\x00R\x04exit\x12?\n" +
	"\x05ready\x18\x04 \x01(\v2'.axnoded.internal.apipb.v1.ProcessReadyH\x00R\x05readyB\t\n" +
	"\apayloadBAZ?github.com/cofy-x/axern/runtime/axnoded/internal/apipb/v1;apipbb\x06proto3"

var (
	file_internal_apipb_v1_process_proto_rawDescOnce sync.Once
	file_internal_apipb_v1_process_proto_rawDescData []byte
)

func file_internal_apipb_v1_process_proto_rawDescGZIP() []byte {
	file_internal_apipb_v1_process_proto_rawDescOnce.Do(func() {
		file_internal_apipb_v1_process_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_apipb_v1_process_proto_rawDesc), len(file_internal_apipb_v1_process_proto_rawDesc)))
	})
	return file_internal_apipb_v1_process_proto_rawDescData
}

var file_internal_apipb_v1_process_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_internal_apipb_v1_process_proto_goTypes = []any{
	(*ExecRequest)(nil),          // 0: axnoded.internal.apipb.v1.ExecRequest
	(*ManagedProxySpec)(nil),     // 1: axnoded.internal.apipb.v1.ManagedProxySpec
	(*ManagedProxyReport)(nil),   // 2: axnoded.internal.apipb.v1.ManagedProxyReport
	(*ExecResponse)(nil),         // 3: axnoded.internal.apipb.v1.ExecResponse
	(*ExecStreamOpen)(nil),       // 4: axnoded.internal.apipb.v1.ExecStreamOpen
	(*ExecStreamRequest)(nil),    // 5: axnoded.internal.apipb.v1.ExecStreamRequest
	(*ExecExit)(nil),             // 6: axnoded.internal.apipb.v1.ExecExit
	(*ExecStreamResponse)(nil),   // 7: axnoded.internal.apipb.v1.ExecStreamResponse
	(*ProcessOpen)(nil),          // 8: axnoded.internal.apipb.v1.ProcessOpen
	(*ProcessSignal)(nil),        // 9: axnoded.internal.apipb.v1.ProcessSignal
	(*ProcessReady)(nil),         // 10: axnoded.internal.apipb.v1.ProcessReady
	(*ProcessRequest)(nil),       // 11: axnoded.internal.apipb.v1.ProcessRequest
	(*ProcessResponse)(nil),      // 12: axnoded.internal.apipb.v1.ProcessResponse
	(*ImageProcessMount)(nil),    // 13: axnoded.internal.apipb.v1.ImageProcessMount
	(*ImageProcessSpec)(nil),     // 14: axnoded.internal.apipb.v1.ImageProcessSpec
	(*ExecImageRequest)(nil),     // 15: axnoded.internal.apipb.v1.ExecImageRequest
	(*ExecImageResponse)(nil),    // 16: axnoded.internal.apipb.v1.ExecImageResponse
	(*ProcessImageOpen)(nil),     // 17: axnoded.internal.apipb.v1.ProcessImageOpen
	(*ProcessImageRequest)(nil),  // 18: axnoded.internal.apipb.v1.ProcessImageRequest
	(*ProcessImageResponse)(nil), // 19: axnoded.internal.apipb.v1.ProcessImageResponse
	nil,                          // 20: axnoded.internal.apipb.v1.ExecRequest.EnvEntry
	nil,                          // 21: axnoded.internal.apipb.v1.ExecStreamOpen.EnvEntry
	nil,                          // 22: axnoded.internal.apipb.v1.ProcessOpen.EnvEntry
	nil,                          // 23: axnoded.internal.apipb.v1.ImageProcessSpec.EnvEntry
	(*TerminalResize)(nil),       // 24: axnoded.internal.apipb.v1.TerminalResize
}
var file_internal_apipb_v1_process_proto_depIdxs = []int32{
	20, // 0: axnoded.internal.apipb.v1.ExecRequest.env:type_name -> axnoded.internal.apipb.v1.ExecRequest.EnvEntry
	1,  // 1: axnoded.internal.apipb.v1.ExecRequest.managed_proxy:type_name -> axnoded.internal.apipb.v1.ManagedProxySpec
	2,  // 2: axnoded.internal.apipb.v1.ExecResponse.managed_proxy_report:type_name -> axnoded.internal.apipb.v1.ManagedProxyReport
	21, // 3: axnoded.internal.apipb.v1.ExecStreamOpen.env:type_name -> axnoded.internal.apipb.v1.ExecStreamOpen.EnvEntry
	24, // 4: axnoded.internal.apipb.v1.ExecStreamOpen.initial_size:type_name -> axnoded.internal.apipb.v1.TerminalResize
	1,  // 5: axnoded.internal.apipb.v1.ExecStreamOpen.managed_proxy:type_name -> axnoded.internal.apipb.v1.ManagedProxySpec
	4,  // 6: axnoded.internal.apipb.v1.ExecStreamRequest.open:type_name -> axnoded.internal.apipb.v1.ExecStreamOpen
	24, // 7: axnoded.internal.apipb.v1.ExecStreamRequest.resize:type_name -> axnoded.internal.apipb.v1.TerminalResize
	2,  // 8: axnoded.internal.apipb.v1.ExecExit.managed_proxy_report:type_name -> axnoded.internal.apipb.v1.ManagedProxyReport
	6,  // 9: axnoded.internal.apipb.v1.ExecStreamResponse.exit:type_name -> axnoded.internal.apipb.v1.ExecExit
	22, // 10: axnoded.internal.apipb.v1.ProcessOpen.env:type_name -> axnoded.internal.apipb.v1.ProcessOpen.EnvEntry
	1,  // 11: axnoded.internal.apipb.v1.ProcessOpen.managed_proxy:type_name -> axnoded.internal.apipb.v1.ManagedProxySpec
	8,  // 12: axnoded.internal.apipb.v1.ProcessRequest.open:type_name -> axnoded.internal.apipb.v1.ProcessOpen
	24, // 13: axnoded.internal.apipb.v1.ProcessRequest.resize:type_name -> axnoded.internal.apipb.v1.TerminalResize
	9,  // 14: axnoded.internal.apipb.v1.ProcessRequest.signal:type_name -> axnoded.internal.apipb.v1.ProcessSignal
	6,  // 15: axnoded.internal.apipb.v1.ProcessResponse.exit:type_name -> axnoded.internal.apipb.v1.ExecExit
	10, // 16: axnoded.internal.apipb.v1.ProcessResponse.ready:type_name -> axnoded.internal.apipb.v1.ProcessReady
	23, // 17: axnoded.internal.apipb.v1.ImageProcessSpec.env:type_name -> axnoded.internal.apipb.v1.ImageProcessSpec.EnvEntry
	13, // 18: axnoded.internal.apipb.v1.ImageProcessSpec.mounts:type_name -> axnoded.internal.apipb.v1.ImageProcessMount
	1,  // 19: axnoded.internal.apipb.v1.ImageProcessSpec.managed_proxy:type_name -> axnoded.internal.apipb.v1.ManagedProxySpec
	14, // 20: axnoded.internal.apipb.v1.ExecImageRequest.spec:type_name -> axnoded.internal.apipb.v1.ImageProcessSpec
	2,  // 21: axnoded.internal.apipb.v1.ExecImageResponse.managed_proxy_report:type_name -> axnoded.internal.apipb.v1.ManagedProxyReport
	14, // 22: axnoded.internal.apipb.v1.ProcessImageOpen.spec:type_name -> axnoded.internal.apipb.v1.ImageProcessSpec
	17, // 23: axnoded.internal.apipb.v1.ProcessImageRequest.open:type_name -> axnoded.internal.apipb.v1.ProcessImageOpen
	24, // 24: axnoded.internal.apipb.v1.ProcessImageRequest.resize:type_name -> axnoded.internal.apipb.v1.TerminalResize
	9,  // 25: axnoded.internal.apipb.v1.ProcessImageRequest.signal:type_name -> axnoded.internal.apipb.v1.ProcessSignal
	6,  // 26: axnoded.internal.apipb.v1.ProcessImageResponse.exit:type_name -> axnoded.internal.apipb.v1.ExecExit
	10, // 27: axnoded.internal.apipb.v1.ProcessImageResponse.ready:type_name -> axnoded.internal.apipb.v1.ProcessReady
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_internal_apipb_v1_process_proto_init() }
func file_internal_apipb_v1_process_proto_init() {
	if File_internal_apipb_v1_process_proto != nil {
		return
	}
	file_internal_apipb_v1_axnoded_internal_proto_init()
	file_internal_apipb_v1_process_proto_msgTypes[5].OneofWrappers = []any{
		(*ExecStreamRequest_Open)(nil),
		(*ExecStreamRequest_Stdin)(nil),
		(*ExecStreamRequest_Resize)(nil),
		(*ExecStreamRequest_CloseStdin)(nil),
	}
	file_internal_apipb_v1_process_proto_msgTypes[7].OneofWrappers = []any{
		(*ExecStreamResponse_Stdout)(nil),
		(*ExecStreamResponse_Stderr)(nil),
		(*ExecStreamResponse_Exit)(nil),
	}
	file_internal_apipb_v1_process_proto_msgTypes[11].OneofWrappers = []any{
		(*ProcessRequest_Open)(nil),
		(*ProcessRequest_Stdin)(nil),
		(*ProcessRequest_Resize)(nil),
		(*ProcessRequest_CloseStdin)(nil),
		(*ProcessRequest_Signal)(nil),
	}
	file_internal_apipb_v1_process_proto_msgTypes[12].OneofWrappers = []any{
		(*ProcessResponse_Stdout)(nil),
		(*ProcessResponse_Stderr)(nil),
		(*ProcessResponse_Exit)(nil),
		(*ProcessResponse_Ready)(nil),
	}
	file_internal_apipb_v1_process_proto_msgTypes[18].OneofWrappers = []any{
		(*ProcessImageRequest_Open)(nil),
		(*ProcessImageRequest_Stdin)(nil),
		(*ProcessImageRequest_Resize)(nil),
		(*ProcessImageRequest_CloseStdin)(nil),
		(*ProcessImageRequest_Signal)(nil),
	}
	file_internal_apipb_v1_process_proto_msgTypes[19].OneofWrappers = []any{
		(*ProcessImageResponse_Stdout)(nil),
		(*ProcessImageResponse_Stderr)(nil),
		(*ProcessImageResponse_Exit)(nil),
		(*ProcessImageResponse_Ready)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_apipb_v1_process_proto_rawDesc), len(file_internal_apipb_v1_process_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_apipb_v1_process_proto_goTypes,
		DependencyIndexes: file_internal_apipb_v1_process_proto_depIdxs,
		MessageInfos:      file_internal_apipb_v1_process_proto_msgTypes,
	}.Build()
	File_internal_apipb_v1_process_proto = out.File
	file_internal_apipb_v1_process_proto_goTypes = nil
	file_internal_apipb_v1_process_proto_depIdxs = nil
}
