package config

import "flag"

func newFlagSet(cfg *Config) *flag.FlagSet {
	flags := flag.NewFlagSet("gatewayd", flag.ContinueOnError)
	flags.StringVar(&cfg.HTTPAddress, "http-address", cfg.HTTPAddress, "gateway HTTP listen address")
	flags.StringVar(&cfg.ControlEdgeAddress, "control-edge-address", cfg.ControlEdgeAddress, "public control-plane gRPC edge listen address")
	flags.StringVar(&cfg.ControlEdgeTLSCACert, "control-edge-tls-ca-cert", cfg.ControlEdgeTLSCACert, "client CA certificate for gateway control edge mTLS")
	flags.StringVar(&cfg.ControlEdgeTLSCert, "control-edge-tls-cert", cfg.ControlEdgeTLSCert, "server certificate for gateway control edge mTLS")
	flags.StringVar(&cfg.ControlEdgeTLSKey, "control-edge-tls-key", cfg.ControlEdgeTLSKey, "server key for gateway control edge mTLS")
	flags.StringVar(&cfg.TunnelRelayTarget, "tunnel-relay-target", cfg.TunnelRelayTarget, "internal tunneld relay gRPC target")
	flags.StringVar(&cfg.TunnelRelayTLSCACert, "tunnel-relay-tls-ca-cert", cfg.TunnelRelayTLSCACert, "CA certificate for internal tunneld relay TLS")
	flags.StringVar(&cfg.TunnelRelayTLSServerName, "tunnel-relay-tls-server-name", cfg.TunnelRelayTLSServerName, "server name used to verify internal tunneld relay TLS")
	flags.StringVar(&cfg.ControlTarget, "control-target", cfg.ControlTarget, "controld gRPC target")
	flags.StringVar(&cfg.TLSCACert, "tls-ca-cert", cfg.TLSCACert, "CA certificate for controld mTLS")
	flags.StringVar(&cfg.TLSCert, "tls-cert", cfg.TLSCert, "gateway client certificate for controld mTLS")
	flags.StringVar(&cfg.TLSKey, "tls-key", cfg.TLSKey, "gateway client key for controld mTLS")
	flags.StringVar(&cfg.DevToken, "dev-token", cfg.DevToken, "local development bearer token for protected gateway routes")
	flags.BoolVar(&cfg.RequireHTTPAuth, "require-http-auth", cfg.RequireHTTPAuth, "require bearer token for service HTTP routes")
	flags.BoolVar(&cfg.SSHEnabled, "ssh-enabled", cfg.SSHEnabled, "enable SSH-compatible terminal listener")
	flags.StringVar(&cfg.SSHAddress, "ssh-address", cfg.SSHAddress, "SSH-compatible terminal listen address")
	flags.StringVar(&cfg.SSHHostKey, "ssh-host-key", cfg.SSHHostKey, "private host key path for SSH-compatible terminal listener")
	flags.StringVar(&cfg.SSHAuthorizedKeys, "ssh-authorized-keys", cfg.SSHAuthorizedKeys, "authorized_keys path for SSH-compatible terminal public key authentication")
	flags.BoolVar(&cfg.DashboardEnabled, "dashboard-enabled", cfg.DashboardEnabled, "enable local gateway terminal dashboard")
	flags.StringVar(&cfg.DashboardVendorDir, "dashboard-vendor-dir", cfg.DashboardVendorDir, "directory containing downloaded dashboard vendor assets")
	flags.DurationVar(&cfg.RouteCacheTTL, "route-cache-ttl", cfg.RouteCacheTTL, "service route cache TTL")
	flags.IntVar(&cfg.RouteCacheMaxEntries, "route-cache-max-entries", cfg.RouteCacheMaxEntries, "maximum service route cache entries")
	flags.DurationVar(&cfg.ControlDialTimeout, "control-dial-timeout", cfg.ControlDialTimeout, "controld dial timeout")
	flags.DurationVar(&cfg.ReadHeaderTimeout, "read-header-timeout", cfg.ReadHeaderTimeout, "HTTP server read header timeout")
	flags.DurationVar(&cfg.ReadTimeout, "read-timeout", cfg.ReadTimeout, "HTTP server read timeout")
	flags.DurationVar(&cfg.WriteTimeout, "write-timeout", cfg.WriteTimeout, "HTTP server write timeout")
	flags.DurationVar(&cfg.IdleTimeout, "idle-timeout", cfg.IdleTimeout, "HTTP server idle timeout")
	flags.DurationVar(&cfg.ServiceUpstreamTimeout, "service-upstream-timeout", cfg.ServiceUpstreamTimeout, "service proxy upstream timeout")
	flags.Int64Var(&cfg.ServiceMaxRequestBodyBytes, "service-max-request-body-bytes", cfg.ServiceMaxRequestBodyBytes, "maximum service request body bytes")
	flags.IntVar(&cfg.ServiceEndpointRetryAttempts, "service-endpoint-retry-attempts", cfg.ServiceEndpointRetryAttempts, "maximum total service proxy attempts across lease refresh and endpoint failover")
	flags.DurationVar(&cfg.ServiceEndpointQuarantineTTL, "service-endpoint-quarantine-ttl", cfg.ServiceEndpointQuarantineTTL, "duration to avoid a service endpoint after retryable pre-upstream proxy failure")
	flags.DurationVar(&cfg.TerminalIdleTimeout, "terminal-idle-timeout", cfg.TerminalIdleTimeout, "terminal websocket idle timeout")
	flags.DurationVar(&cfg.TerminalMaxDuration, "terminal-max-duration", cfg.TerminalMaxDuration, "terminal websocket maximum session duration")
	flags.Int64Var(&cfg.TerminalMaxMessageBytes, "terminal-max-message-bytes", cfg.TerminalMaxMessageBytes, "terminal websocket maximum message bytes")
	flags.IntVar(&cfg.LeaseRetryAttempts, "lease-retry-attempts", cfg.LeaseRetryAttempts, "terminal and NodeSandbox execution lease attempts")
	flags.DurationVar(&cfg.LeaseRetryBaseDelay, "lease-retry-base-delay", cfg.LeaseRetryBaseDelay, "transient lease retry base delay")
	flags.IntVar(&cfg.ArtifactMaxConcurrent, "artifact-max-concurrent", cfg.ArtifactMaxConcurrent, "maximum concurrent artifact downloads")
	flags.IntVar(&cfg.ArtifactChunkBytes, "artifact-chunk-bytes", cfg.ArtifactChunkBytes, "artifact gRPC stream chunk size")
	flags.DurationVar(&cfg.ArtifactUpstreamTimeout, "artifact-upstream-timeout", cfg.ArtifactUpstreamTimeout, "artifact object-store response header timeout")
	flags.Int64Var(&cfg.ArtifactMaxBytes, "artifact-max-bytes", cfg.ArtifactMaxBytes, "maximum artifact size")
	flags.StringVar(&cfg.LogLevel, "log-level", cfg.LogLevel, "log level: debug|info|warn|error")
	return flags
}
