package config

import "flag"

func newFlagSet(cfg *Config) *flag.FlagSet {
	flags := flag.NewFlagSet("gatewayd", flag.ContinueOnError)
	flags.StringVar(&cfg.HTTPAddress, "http-address", cfg.HTTPAddress, "gateway HTTP listen address")
	flags.StringVar(&cfg.ControlEdgeAddress, "control-edge-address", cfg.ControlEdgeAddress, "public control-plane gRPC edge listen address")
	flags.StringVar(&cfg.ControlEdgeTLSCACert, "control-edge-tls-ca-cert", cfg.ControlEdgeTLSCACert, "client CA certificate for gateway control edge mTLS")
	flags.StringVar(&cfg.ControlEdgeTLSCert, "control-edge-tls-cert", cfg.ControlEdgeTLSCert, "server certificate for gateway control edge mTLS")
	flags.StringVar(&cfg.ControlEdgeTLSKey, "control-edge-tls-key", cfg.ControlEdgeTLSKey, "server key for gateway control edge mTLS")
	flags.StringVar(&cfg.TunnelRelayTarget, "tunnel-relay-target", cfg.TunnelRelayTarget, "internal tunneld relay gRPC target")
	flags.StringVar(&cfg.TunnelRelayTLSCACert, "tunnel-relay-tls-ca-cert", cfg.TunnelRelayTLSCACert, "CA certificate for internal tunneld relay TLS")
	flags.StringVar(&cfg.TunnelRelayTLSServerName, "tunnel-relay-tls-server-name", cfg.TunnelRelayTLSServerName, "server name used to verify internal tunneld relay TLS")
	flags.StringVar(&cfg.ControlTarget, "control-target", cfg.ControlTarget, "controld gRPC target")
	flags.StringVar(&cfg.TLSCACert, "tls-ca-cert", cfg.TLSCACert, "CA certificate for controld mTLS")
	flags.StringVar(&cfg.TLSCert, "tls-cert", cfg.TLSCert, "gateway client certificate for controld mTLS")
	flags.StringVar(&cfg.TLSKey, "tls-key", cfg.TLSKey, "gateway client key for controld mTLS")
	flags.StringVar(&cfg.NodeTLSCACert, "node-tls-ca-cert", cfg.NodeTLSCACert, "CA certificate used to verify axnoded mTLS")
	flags.StringVar(&cfg.NodeTLSCert, "node-tls-cert", cfg.NodeTLSCert, "gatewayd client certificate for axnoded mTLS")
	flags.StringVar(&cfg.NodeTLSKey, "node-tls-key", cfg.NodeTLSKey, "gatewayd client key for axnoded mTLS")
	flags.StringVar(&cfg.NodeTLSServerName, "node-tls-server-name", cfg.NodeTLSServerName, "server identity used to verify axnoded mTLS")
	flags.StringVar(&cfg.DevToken, "dev-token", cfg.DevToken, "local development bearer token for protected gateway routes")
	flags.BoolVar(&cfg.SSHEnabled, "ssh-enabled", cfg.SSHEnabled, "enable SSH-compatible terminal listener")
	flags.StringVar(&cfg.SSHAddress, "ssh-address", cfg.SSHAddress, "SSH-compatible terminal listen address")
	flags.StringVar(&cfg.SSHHostKey, "ssh-host-key", cfg.SSHHostKey, "private host key path for SSH-compatible terminal listener")
	flags.StringVar(&cfg.SSHAuthorizedKeys, "ssh-authorized-keys", cfg.SSHAuthorizedKeys, "authorized_keys path for SSH-compatible terminal public key authentication")
	flags.DurationVar(&cfg.ControlDialTimeout, "control-dial-timeout", cfg.ControlDialTimeout, "controld dial timeout")
	flags.DurationVar(&cfg.ReadHeaderTimeout, "read-header-timeout", cfg.ReadHeaderTimeout, "HTTP server read header timeout")
	flags.DurationVar(&cfg.ReadTimeout, "read-timeout", cfg.ReadTimeout, "HTTP server read timeout")
	flags.DurationVar(&cfg.WriteTimeout, "write-timeout", cfg.WriteTimeout, "HTTP server write timeout")
	flags.DurationVar(&cfg.IdleTimeout, "idle-timeout", cfg.IdleTimeout, "HTTP server idle timeout")
	flags.DurationVar(&cfg.TerminalIdleTimeout, "terminal-idle-timeout", cfg.TerminalIdleTimeout, "terminal websocket idle timeout")
	flags.DurationVar(&cfg.TerminalMaxDuration, "terminal-max-duration", cfg.TerminalMaxDuration, "terminal websocket maximum session duration")
	flags.Int64Var(&cfg.TerminalMaxMessageBytes, "terminal-max-message-bytes", cfg.TerminalMaxMessageBytes, "terminal websocket maximum message bytes")
	flags.IntVar(&cfg.AccessGrantRetryAttempts, "access-grant-retry-attempts", cfg.AccessGrantRetryAttempts, "terminal and NodeSandbox allocation access grant attempts")
	flags.DurationVar(&cfg.AccessGrantRetryBaseDelay, "access-grant-retry-base-delay", cfg.AccessGrantRetryBaseDelay, "transient allocation access grant retry base delay")
	flags.StringVar(&cfg.LogLevel, "log-level", cfg.LogLevel, "log level: debug|info|warn|error")
	return flags
}
