#!/usr/bin/env bash
set -euo pipefail

devbox_user="${DEVBOX_USER:-axern}"

if [ -S /var/run/docker.sock ]; then
  sock_gid="$(stat -c '%g' /var/run/docker.sock)"
  docker_group="$(getent group "${sock_gid}" | cut -d: -f1 || true)"
  if [ -z "${docker_group}" ]; then
    docker_group="dockerhost"
    if getent group "${docker_group}" >/dev/null; then
      groupmod -o -g "${sock_gid}" "${docker_group}" >/dev/null 2>&1 || true
    else
      groupadd -o -g "${sock_gid}" "${docker_group}" >/dev/null 2>&1 || true
    fi
  fi
  if [ -n "${docker_group}" ]; then
    usermod -aG "${docker_group}" "${devbox_user}" >/dev/null 2>&1 || true
  fi
fi

if [ -f /host-ssh-authorized-keys ] && id "${devbox_user}" >/dev/null 2>&1; then
  install -d -m 0700 -o "${devbox_user}" -g "${devbox_user}" "/home/${devbox_user}/.ssh"
  tmp_keys="$(mktemp)"
  cat /host-ssh-authorized-keys >> "${tmp_keys}"
  if [ -s "${tmp_keys}" ]; then
    sort -u "${tmp_keys}" > "/home/${devbox_user}/.ssh/authorized_keys"
    chown "${devbox_user}:${devbox_user}" "/home/${devbox_user}/.ssh/authorized_keys"
    chmod 0600 "/home/${devbox_user}/.ssh/authorized_keys"
  fi
  rm -f "${tmp_keys}"
fi

ssh-keygen -A >/dev/null 2>&1 || true

if id "${devbox_user}" >/dev/null 2>&1; then
  env_file="/home/${devbox_user}/.axern-devbox-env"
  ssh_env_file="/home/${devbox_user}/.ssh/environment"
  install -d -m 0700 -o "${devbox_user}" -g "${devbox_user}" "/home/${devbox_user}/.ssh"

  axern_dev_workspace="${AXERN_DEV_WORKSPACE:-}"
  axern_endpoint="${AXERN_ENDPOINT:-127.0.0.1:24000}"
  axern_tls_ca_cert="${AXERN_TLS_CA_CERT:-${axern_dev_workspace}/.dev/certs/ca.crt}"
  axern_tls_cert="${AXERN_TLS_CERT:-${axern_dev_workspace}/.dev/certs/client.crt}"
  axern_tls_key="${AXERN_TLS_KEY:-${axern_dev_workspace}/.dev/certs/client.key}"
  axnoded_socket="${AXNODED_SOCKET:-${axern_dev_workspace}/.dev/run/axnoded.sock}"
  imagemgr_socket="${IMAGEMGR_SOCKET:-${axern_dev_workspace}/.dev/run/imagemgr.sock}"
  goproxy="${GOPROXY:-https://proxy.golang.org,direct}"
  devbox_path="${PATH}"
  if [ -n "${axern_dev_workspace}" ]; then
    devbox_path="${axern_dev_workspace}/bin:${devbox_path}"
  fi

  {
    printf '# Generated by docker/devbox/entrypoint.sh\n'
    printf 'export PATH=%q\n' "${devbox_path}"
    printf 'export AXERN_DEV_WORKSPACE=%q\n' "${axern_dev_workspace}"
    printf 'export AXERN_ENDPOINT=%q\n' "${axern_endpoint}"
    printf 'export AXERN_TLS_CA_CERT=%q\n' "${axern_tls_ca_cert}"
    printf 'export AXERN_TLS_CERT=%q\n' "${axern_tls_cert}"
    printf 'export AXERN_TLS_KEY=%q\n' "${axern_tls_key}"
    printf 'export AXNODED_SOCKET=%q\n' "${axnoded_socket}"
    printf 'export IMAGEMGR_SOCKET=%q\n' "${imagemgr_socket}"
    printf 'export GOPROXY=%q\n' "${goproxy}"
    printf 'export GOTOOLCHAIN=%q\n' "${GOTOOLCHAIN:-local}"
    [ -n "${HTTP_PROXY:-}" ] && printf 'export HTTP_PROXY=%q\n' "${HTTP_PROXY}"
    [ -n "${HTTPS_PROXY:-}" ] && printf 'export HTTPS_PROXY=%q\n' "${HTTPS_PROXY}"
    [ -n "${NO_PROXY:-}" ] && printf 'export NO_PROXY=%q\n' "${NO_PROXY}"
    [ -n "${http_proxy:-}" ] && printf 'export http_proxy=%q\n' "${http_proxy}"
    [ -n "${https_proxy:-}" ] && printf 'export https_proxy=%q\n' "${https_proxy}"
    [ -n "${no_proxy:-}" ] && printf 'export no_proxy=%q\n' "${no_proxy}"
  } > "${env_file}"

  {
    printf 'PATH=%s\n' "${devbox_path}"
    printf 'AXERN_DEV_WORKSPACE=%s\n' "${axern_dev_workspace}"
    printf 'AXERN_ENDPOINT=%s\n' "${axern_endpoint}"
    printf 'AXERN_TLS_CA_CERT=%s\n' "${axern_tls_ca_cert}"
    printf 'AXERN_TLS_CERT=%s\n' "${axern_tls_cert}"
    printf 'AXERN_TLS_KEY=%s\n' "${axern_tls_key}"
    printf 'AXNODED_SOCKET=%s\n' "${axnoded_socket}"
    printf 'IMAGEMGR_SOCKET=%s\n' "${imagemgr_socket}"
    printf 'GOPROXY=%s\n' "${goproxy}"
    printf 'GOTOOLCHAIN=%s\n' "${GOTOOLCHAIN:-local}"
    [ -n "${HTTP_PROXY:-}" ] && printf 'HTTP_PROXY=%s\n' "${HTTP_PROXY}"
    [ -n "${HTTPS_PROXY:-}" ] && printf 'HTTPS_PROXY=%s\n' "${HTTPS_PROXY}"
    [ -n "${NO_PROXY:-}" ] && printf 'NO_PROXY=%s\n' "${NO_PROXY}"
    [ -n "${http_proxy:-}" ] && printf 'http_proxy=%s\n' "${http_proxy}"
    [ -n "${https_proxy:-}" ] && printf 'https_proxy=%s\n' "${https_proxy}"
    [ -n "${no_proxy:-}" ] && printf 'no_proxy=%s\n' "${no_proxy}"
  } > "${ssh_env_file}"

  chown "${devbox_user}:${devbox_user}" "${env_file}"
  chown "${devbox_user}:${devbox_user}" "${ssh_env_file}"
  chmod 0644 "${env_file}"
  chmod 0600 "${ssh_env_file}"
fi

if [ "${1:-}" = "/usr/bin/supervisord" ] || [ "${1:-}" = "supervisord" ] || [ "${1:-}" = "/usr/sbin/sshd" ]; then
  exec "$@"
fi

if [ "$(id -u)" -eq 0 ] && id "${devbox_user}" >/dev/null 2>&1; then
  exec gosu "${devbox_user}" "$@"
fi

exec "$@"
