package observability

const (
	SpanHTTP                             = "controld.http"
	SpanGatewayResolveAllocationTerminal = "controld.gateway.resolve_allocation_terminal"
	SpanNodeReport                       = "controld.node.report"
	SpanAllocationReportLifecycle        = "controld.allocation.report_status"
	SpanEnvironmentCreate                = "controld.environment.create"
	SpanEnvironmentDelete                = "controld.environment.delete"
	SpanRunCreate                        = "controld.run.create"
	SpanRunCancel                        = "controld.run.cancel"
	SpanNamespaceCreate                  = "controld.namespace.create"
	SpanNamespaceGet                     = "controld.namespace.get"
	SpanNamespaceList                    = "controld.namespace.list"
	SpanNamespaceDelete                  = "controld.namespace.delete"
	SpanQuotaGet                         = "controld.quota.get"
	SpanQuotaList                        = "controld.quota.list"
	SpanQuotaSet                         = "controld.quota.set"
	SpanQuotaUnset                       = "controld.quota.unset"
	SpanTunnelCreate                     = "controld.tunnel.create"
	SpanTunnelGet                        = "controld.tunnel.get"
	SpanTunnelList                       = "controld.tunnel.list"
	SpanTunnelListEvents                 = "controld.tunnel.list_events"
	SpanTunnelInspect                    = "controld.tunnel.inspect"
	SpanTunnelRevoke                     = "controld.tunnel.revoke"
	SpanTunnelRenew                      = "controld.tunnel.renew"
	SpanRetentionCleanup                 = "controld.retention.cleanup"
)
