package observability

const (
	SpanHTTP                             = "controld.http"
	SpanGatewayResolveServiceRoute       = "controld.gateway.resolve_service_route"
	SpanGatewayResolveAllocationTerminal = "controld.gateway.resolve_allocation_terminal"
	SpanNodeReport                       = "controld.node.report"
	SpanAllocationReportStatus           = "controld.allocation.report_status"
	SpanServiceEvent                     = "controld.service.event"
	SpanServiceCreate                    = "controld.service.create"
	SpanServiceUpdate                    = "controld.service.update"
	SpanServiceDelete                    = "controld.service.delete"
	SpanServicePurge                     = "controld.service.purge"
	SpanServiceListReplicas              = "controld.service.list_replicas"
	SpanServiceListEvents                = "controld.service.list_events"
	SpanServiceReconcilePending          = "controld.service.reconcile_pending"
	SpanServiceSync                      = "controld.service.sync"
	SpanEnvironmentCreate                = "controld.environment.create"
	SpanEnvironmentDelete                = "controld.environment.delete"
	SpanRunCreate                        = "controld.run.create"
	SpanRunCancel                        = "controld.run.cancel"
	SpanNamespaceCreate                  = "controld.namespace.create"
	SpanNamespaceGet                     = "controld.namespace.get"
	SpanNamespaceList                    = "controld.namespace.list"
	SpanNamespaceDelete                  = "controld.namespace.delete"
	SpanQuotaGet                         = "controld.quota.get"
	SpanQuotaList                        = "controld.quota.list"
	SpanQuotaSet                         = "controld.quota.set"
	SpanQuotaUnset                       = "controld.quota.unset"
	SpanTunnelCreate                     = "controld.tunnel.create"
	SpanTunnelGet                        = "controld.tunnel.get"
	SpanTunnelList                       = "controld.tunnel.list"
	SpanTunnelListEvents                 = "controld.tunnel.list_events"
	SpanTunnelInspect                    = "controld.tunnel.inspect"
	SpanTunnelRevoke                     = "controld.tunnel.revoke"
	SpanTunnelRenew                      = "controld.tunnel.renew"
	SpanRetentionCleanup                 = "controld.retention.cleanup"
)
