[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:xvfb]
priority=1
command=/usr/bin/Xvfb :99 -screen 0 1280x720x24 -nolisten tcp
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/xvfb.out.log
stderr_logfile=/var/log/supervisor/xvfb.err.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5

[program:fluxbox]
priority=2
command=/usr/bin/fluxbox
environment=DISPLAY=":99"
user=axern
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/fluxbox.out.log
stderr_logfile=/var/log/supervisor/fluxbox.err.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5

[program:sshd]
priority=3
command=/usr/sbin/sshd -D
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/sshd.out.log
stderr_logfile=/var/log/supervisor/sshd.err.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5

[program:nginx]
priority=4
command=/usr/sbin/nginx -g "daemon off;"
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/nginx.out.log
stderr_logfile=/var/log/supervisor/nginx.err.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
