package dataplane

const (
	KernelStatAttachSuccess uint32 = iota
	KernelStatAttachError
	KernelStatSNATHit
	KernelStatSNATRevHit
	KernelStatSNATFwdHit
	KernelStatSNATUDPSamePortHit
	KernelStatSNATUDPPortRewriteHit
	KernelStatSNATUDPChecksumPresentHit
	KernelStatSNATMappingProgrammed
	KernelStatSNATAllocCollision
	KernelStatSNATFallbackHit
	KernelStatSNATAllocExhausted
	KernelStatSNATTCPNonSynMiss
	KernelStatSNATTCPNonSynMissFIN
	KernelStatSNATTCPNonSynMissRST
	KernelStatSNATTCPNonSynMissACK
	KernelStatSNATTCPNonSynMissOther
	KernelStatSNATFullCloseReclaim
	KernelStatSNATFullCloseMark
	KernelStatSNATTCPFullCloseDelete
	KernelStatSNATTCPFullCloseDeleteFwd
	KernelStatSNATTCPFullCloseDeleteRev
	KernelStatSNATTCPNonSynMissFwdLookup
	KernelStatSNATTCPNonSynMissFwdHostMismatch
	KernelStatSNATTCPRevMiss
	KernelStatSNATTCPRevMissSynACK
	KernelStatSNATTCPRevMissFIN
	KernelStatSNATTCPRevMissRST
	KernelStatSNATTCPRevMissACK
	KernelStatSNATTCPRevMissOther
	KernelStatNativeRouteSkip
)
