# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from axern.control.secret.v1 import secret_pb2 as axern_dot_control_dot_secret_dot_v1_dot_secret__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in axern/control/secret/v1/secret_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SecretControlStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSecret = channel.unary_unary(
                '/axern.control.secret.v1.SecretControl/CreateSecret',
                request_serializer=axern_dot_control_dot_secret_dot_v1_dot_secret__pb2.CreateSecretRequest.SerializeToString,
                response_deserializer=axern_dot_control_dot_secret_dot_v1_dot_secret__pb2.CreateSecretResponse.FromString,
                _registered_method=True)
        self.GetSecret = channel.unary_unary(
                '/axern.control.secret.v1.SecretControl/GetSecret',
                request_serializer=axern_dot_control_dot_secret_dot_v1_dot_secret__pb2.GetSecretRequest.SerializeToString,
                response_deserializer=axern_dot_control_dot_secret_dot_v1_dot_secret__pb2.GetSecretResponse.FromString,
                _registered_method=True)
        self.ListSecrets = channel.unary_unary(
                '/axern.control.secret.v1.SecretControl/ListSecrets',
                request_serializer=axern_dot_control_dot_secret_dot_v1_dot_secret__pb2.ListSecretsRequest.SerializeToString,
                response_deserializer=axern_dot_control_dot_secret_dot_v1_dot_secret__pb2.ListSecretsResponse.FromString,
                _registered_method=True)
        self.DeleteSecret = channel.unary_unary(
                '/axern.control.secret.v1.SecretControl/DeleteSecret',
                request_serializer=axern_dot_control_dot_secret_dot_v1_dot_secret__pb2.DeleteSecretRequest.SerializeToString,
                response_deserializer=axern_dot_control_dot_secret_dot_v1_dot_secret__pb2.DeleteSecretResponse.FromString,
                _registered_method=True)


class SecretControlServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSecrets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SecretControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSecret,
                    request_deserializer=axern_dot_control_dot_secret_dot_v1_dot_secret__pb2.CreateSecretRequest.FromString,
                    response_serializer=axern_dot_control_dot_secret_dot_v1_dot_secret__pb2.CreateSecretResponse.SerializeToString,
            ),
            'GetSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSecret,
                    request_deserializer=axern_dot_control_dot_secret_dot_v1_dot_secret__pb2.GetSecretRequest.FromString,
                    response_serializer=axern_dot_control_dot_secret_dot_v1_dot_secret__pb2.GetSecretResponse.SerializeToString,
            ),
            'ListSecrets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSecrets,
                    request_deserializer=axern_dot_control_dot_secret_dot_v1_dot_secret__pb2.ListSecretsRequest.FromString,
                    response_serializer=axern_dot_control_dot_secret_dot_v1_dot_secret__pb2.ListSecretsResponse.SerializeToString,
            ),
            'DeleteSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSecret,
                    request_deserializer=axern_dot_control_dot_secret_dot_v1_dot_secret__pb2.DeleteSecretRequest.FromString,
                    response_serializer=axern_dot_control_dot_secret_dot_v1_dot_secret__pb2.DeleteSecretResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'axern.control.secret.v1.SecretControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('axern.control.secret.v1.SecretControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SecretControl:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.control.secret.v1.SecretControl/CreateSecret',
            axern_dot_control_dot_secret_dot_v1_dot_secret__pb2.CreateSecretRequest.SerializeToString,
            axern_dot_control_dot_secret_dot_v1_dot_secret__pb2.CreateSecretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.control.secret.v1.SecretControl/GetSecret',
            axern_dot_control_dot_secret_dot_v1_dot_secret__pb2.GetSecretRequest.SerializeToString,
            axern_dot_control_dot_secret_dot_v1_dot_secret__pb2.GetSecretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSecrets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.control.secret.v1.SecretControl/ListSecrets',
            axern_dot_control_dot_secret_dot_v1_dot_secret__pb2.ListSecretsRequest.SerializeToString,
            axern_dot_control_dot_secret_dot_v1_dot_secret__pb2.ListSecretsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/axern.control.secret.v1.SecretControl/DeleteSecret',
            axern_dot_control_dot_secret_dot_v1_dot_secret__pb2.DeleteSecretRequest.SerializeToString,
            axern_dot_control_dot_secret_dot_v1_dot_secret__pb2.DeleteSecretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
